/*
 * generated by Xtext 2.29.0
 */
package fr.lcis.castav.vpat.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractVPATValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(fr.lcis.castav.vpat.vPAT.VPATPackage.eINSTANCE);
		return result;
	}
}
