/*
 * generated by Xtext 2.29.0
 */
package fr.lcis.castav.cdml.parser.antlr;

import com.google.inject.Inject;
import fr.lcis.castav.cdml.parser.antlr.internal.InternalCDMLParser;
import fr.lcis.castav.cdml.services.CDMLGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class CDMLParser extends AbstractAntlrParser {

	@Inject
	private CDMLGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalCDMLParser createParser(XtextTokenStream stream) {
		return new InternalCDMLParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Cdml";
	}

	public CDMLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(CDMLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
