/**
 * generated by Xtext 2.29.0
 */
package fr.lcis.castav.cdl.cDL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Boolean Type</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see fr.lcis.castav.cdl.cDL.CDLPackage#getBooleanType()
 * @model
 * @generated
 */
public interface BooleanType extends SimpleType
{
} // BooleanType
