/**
 * generated by Xtext 2.29.0
 */
package fr.lcis.castav.cdl.cDL;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see fr.lcis.castav.cdl.cDL.CDLFactory
 * @model kind="package"
 * @generated
 */
public interface CDLPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "cDL";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.lcis.fr/castav/cdl/CDL";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "cDL";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  CDLPackage eINSTANCE = fr.lcis.castav.cdl.cDL.impl.CDLPackageImpl.init();

  /**
   * The meta object id for the '{@link fr.lcis.castav.cdl.cDL.impl.ContextModelImpl <em>Context Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.lcis.castav.cdl.cDL.impl.ContextModelImpl
   * @see fr.lcis.castav.cdl.cDL.impl.CDLPackageImpl#getContextModel()
   * @generated
   */
  int CONTEXT_MODEL = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTEXT_MODEL__NAME = 0;

  /**
   * The feature id for the '<em><b>Contexts</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTEXT_MODEL__CONTEXTS = 1;

  /**
   * The feature id for the '<em><b>Providers</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTEXT_MODEL__PROVIDERS = 2;

  /**
   * The feature id for the '<em><b>Situations</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTEXT_MODEL__SITUATIONS = 3;

  /**
   * The feature id for the '<em><b>Types</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTEXT_MODEL__TYPES = 4;

  /**
   * The number of structural features of the '<em>Context Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTEXT_MODEL_FEATURE_COUNT = 5;

  /**
   * The meta object id for the '{@link fr.lcis.castav.cdl.cDL.impl.ContextImpl <em>Context</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.lcis.castav.cdl.cDL.impl.ContextImpl
   * @see fr.lcis.castav.cdl.cDL.impl.CDLPackageImpl#getContext()
   * @generated
   */
  int CONTEXT = 1;

  /**
   * The feature id for the '<em><b>Static</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTEXT__STATIC = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTEXT__NAME = 1;

  /**
   * The feature id for the '<em><b>Derived</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTEXT__DERIVED = 2;

  /**
   * The feature id for the '<em><b>Derives</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTEXT__DERIVES = 3;

  /**
   * The feature id for the '<em><b>Providers</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTEXT__PROVIDERS = 4;

  /**
   * The feature id for the '<em><b>Properties</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTEXT__PROPERTIES = 5;

  /**
   * The feature id for the '<em><b>Mappings</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTEXT__MAPPINGS = 6;

  /**
   * The number of structural features of the '<em>Context</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTEXT_FEATURE_COUNT = 7;

  /**
   * The meta object id for the '{@link fr.lcis.castav.cdl.cDL.impl.ContextMappingImpl <em>Context Mapping</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.lcis.castav.cdl.cDL.impl.ContextMappingImpl
   * @see fr.lcis.castav.cdl.cDL.impl.CDLPackageImpl#getContextMapping()
   * @generated
   */
  int CONTEXT_MAPPING = 2;

  /**
   * The feature id for the '<em><b>Ref</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTEXT_MAPPING__REF = 0;

  /**
   * The feature id for the '<em><b>Expression</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTEXT_MAPPING__EXPRESSION = 1;

  /**
   * The number of structural features of the '<em>Context Mapping</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTEXT_MAPPING_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link fr.lcis.castav.cdl.cDL.impl.ProvidersImpl <em>Providers</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.lcis.castav.cdl.cDL.impl.ProvidersImpl
   * @see fr.lcis.castav.cdl.cDL.impl.CDLPackageImpl#getProviders()
   * @generated
   */
  int PROVIDERS = 3;

  /**
   * The feature id for the '<em><b>Providers</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROVIDERS__PROVIDERS = 0;

  /**
   * The number of structural features of the '<em>Providers</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROVIDERS_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link fr.lcis.castav.cdl.cDL.impl.ProviderImpl <em>Provider</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.lcis.castav.cdl.cDL.impl.ProviderImpl
   * @see fr.lcis.castav.cdl.cDL.impl.CDLPackageImpl#getProvider()
   * @generated
   */
  int PROVIDER = 4;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROVIDER__NAME = 0;

  /**
   * The number of structural features of the '<em>Provider</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROVIDER_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link fr.lcis.castav.cdl.cDL.impl.PropertyImpl <em>Property</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.lcis.castav.cdl.cDL.impl.PropertyImpl
   * @see fr.lcis.castav.cdl.cDL.impl.CDLPackageImpl#getProperty()
   * @generated
   */
  int PROPERTY = 5;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROPERTY__NAME = 0;

  /**
   * The feature id for the '<em><b>Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROPERTY__TYPE = 1;

  /**
   * The number of structural features of the '<em>Property</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROPERTY_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link fr.lcis.castav.cdl.cDL.impl.TypeRefImpl <em>Type Ref</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.lcis.castav.cdl.cDL.impl.TypeRefImpl
   * @see fr.lcis.castav.cdl.cDL.impl.CDLPackageImpl#getTypeRef()
   * @generated
   */
  int TYPE_REF = 6;

  /**
   * The feature id for the '<em><b>Ref</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TYPE_REF__REF = 0;

  /**
   * The number of structural features of the '<em>Type Ref</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TYPE_REF_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link fr.lcis.castav.cdl.cDL.impl.DefinedTypeImpl <em>Defined Type</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.lcis.castav.cdl.cDL.impl.DefinedTypeImpl
   * @see fr.lcis.castav.cdl.cDL.impl.CDLPackageImpl#getDefinedType()
   * @generated
   */
  int DEFINED_TYPE = 7;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEFINED_TYPE__NAME = 0;

  /**
   * The feature id for the '<em><b>Values</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEFINED_TYPE__VALUES = 1;

  /**
   * The number of structural features of the '<em>Defined Type</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEFINED_TYPE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link fr.lcis.castav.cdl.cDL.impl.ContextValueImpl <em>Context Value</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.lcis.castav.cdl.cDL.impl.ContextValueImpl
   * @see fr.lcis.castav.cdl.cDL.impl.CDLPackageImpl#getContextValue()
   * @generated
   */
  int CONTEXT_VALUE = 8;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTEXT_VALUE__NAME = 0;

  /**
   * The number of structural features of the '<em>Context Value</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTEXT_VALUE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link fr.lcis.castav.cdl.cDL.impl.SimpleTypeImpl <em>Simple Type</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.lcis.castav.cdl.cDL.impl.SimpleTypeImpl
   * @see fr.lcis.castav.cdl.cDL.impl.CDLPackageImpl#getSimpleType()
   * @generated
   */
  int SIMPLE_TYPE = 9;

  /**
   * The number of structural features of the '<em>Simple Type</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SIMPLE_TYPE_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link fr.lcis.castav.cdl.cDL.impl.StringTypeImpl <em>String Type</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.lcis.castav.cdl.cDL.impl.StringTypeImpl
   * @see fr.lcis.castav.cdl.cDL.impl.CDLPackageImpl#getStringType()
   * @generated
   */
  int STRING_TYPE = 10;

  /**
   * The number of structural features of the '<em>String Type</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STRING_TYPE_FEATURE_COUNT = SIMPLE_TYPE_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link fr.lcis.castav.cdl.cDL.impl.IntegerTypeImpl <em>Integer Type</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.lcis.castav.cdl.cDL.impl.IntegerTypeImpl
   * @see fr.lcis.castav.cdl.cDL.impl.CDLPackageImpl#getIntegerType()
   * @generated
   */
  int INTEGER_TYPE = 11;

  /**
   * The number of structural features of the '<em>Integer Type</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INTEGER_TYPE_FEATURE_COUNT = SIMPLE_TYPE_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link fr.lcis.castav.cdl.cDL.impl.BooleanTypeImpl <em>Boolean Type</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.lcis.castav.cdl.cDL.impl.BooleanTypeImpl
   * @see fr.lcis.castav.cdl.cDL.impl.CDLPackageImpl#getBooleanType()
   * @generated
   */
  int BOOLEAN_TYPE = 12;

  /**
   * The number of structural features of the '<em>Boolean Type</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOOLEAN_TYPE_FEATURE_COUNT = SIMPLE_TYPE_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link fr.lcis.castav.cdl.cDL.impl.DoubleTypeImpl <em>Double Type</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.lcis.castav.cdl.cDL.impl.DoubleTypeImpl
   * @see fr.lcis.castav.cdl.cDL.impl.CDLPackageImpl#getDoubleType()
   * @generated
   */
  int DOUBLE_TYPE = 13;

  /**
   * The number of structural features of the '<em>Double Type</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DOUBLE_TYPE_FEATURE_COUNT = SIMPLE_TYPE_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link fr.lcis.castav.cdl.cDL.impl.SituationImpl <em>Situation</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.lcis.castav.cdl.cDL.impl.SituationImpl
   * @see fr.lcis.castav.cdl.cDL.impl.CDLPackageImpl#getSituation()
   * @generated
   */
  int SITUATION = 14;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SITUATION__NAME = 0;

  /**
   * The feature id for the '<em><b>Expression</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SITUATION__EXPRESSION = 1;

  /**
   * The number of structural features of the '<em>Situation</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SITUATION_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link fr.lcis.castav.cdl.cDL.impl.ContextExpressionImpl <em>Context Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.lcis.castav.cdl.cDL.impl.ContextExpressionImpl
   * @see fr.lcis.castav.cdl.cDL.impl.CDLPackageImpl#getContextExpression()
   * @generated
   */
  int CONTEXT_EXPRESSION = 15;

  /**
   * The feature id for the '<em><b>Ref</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTEXT_EXPRESSION__REF = 0;

  /**
   * The feature id for the '<em><b>Value</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTEXT_EXPRESSION__VALUE = 1;

  /**
   * The feature id for the '<em><b>Expr</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTEXT_EXPRESSION__EXPR = 2;

  /**
   * The number of structural features of the '<em>Context Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTEXT_EXPRESSION_FEATURE_COUNT = 3;


  /**
   * Returns the meta object for class '{@link fr.lcis.castav.cdl.cDL.ContextModel <em>Context Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Context Model</em>'.
   * @see fr.lcis.castav.cdl.cDL.ContextModel
   * @generated
   */
  EClass getContextModel();

  /**
   * Returns the meta object for the attribute '{@link fr.lcis.castav.cdl.cDL.ContextModel#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see fr.lcis.castav.cdl.cDL.ContextModel#getName()
   * @see #getContextModel()
   * @generated
   */
  EAttribute getContextModel_Name();

  /**
   * Returns the meta object for the containment reference list '{@link fr.lcis.castav.cdl.cDL.ContextModel#getContexts <em>Contexts</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Contexts</em>'.
   * @see fr.lcis.castav.cdl.cDL.ContextModel#getContexts()
   * @see #getContextModel()
   * @generated
   */
  EReference getContextModel_Contexts();

  /**
   * Returns the meta object for the containment reference list '{@link fr.lcis.castav.cdl.cDL.ContextModel#getProviders <em>Providers</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Providers</em>'.
   * @see fr.lcis.castav.cdl.cDL.ContextModel#getProviders()
   * @see #getContextModel()
   * @generated
   */
  EReference getContextModel_Providers();

  /**
   * Returns the meta object for the containment reference list '{@link fr.lcis.castav.cdl.cDL.ContextModel#getSituations <em>Situations</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Situations</em>'.
   * @see fr.lcis.castav.cdl.cDL.ContextModel#getSituations()
   * @see #getContextModel()
   * @generated
   */
  EReference getContextModel_Situations();

  /**
   * Returns the meta object for the containment reference list '{@link fr.lcis.castav.cdl.cDL.ContextModel#getTypes <em>Types</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Types</em>'.
   * @see fr.lcis.castav.cdl.cDL.ContextModel#getTypes()
   * @see #getContextModel()
   * @generated
   */
  EReference getContextModel_Types();

  /**
   * Returns the meta object for class '{@link fr.lcis.castav.cdl.cDL.Context <em>Context</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Context</em>'.
   * @see fr.lcis.castav.cdl.cDL.Context
   * @generated
   */
  EClass getContext();

  /**
   * Returns the meta object for the attribute '{@link fr.lcis.castav.cdl.cDL.Context#isStatic <em>Static</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Static</em>'.
   * @see fr.lcis.castav.cdl.cDL.Context#isStatic()
   * @see #getContext()
   * @generated
   */
  EAttribute getContext_Static();

  /**
   * Returns the meta object for the attribute '{@link fr.lcis.castav.cdl.cDL.Context#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see fr.lcis.castav.cdl.cDL.Context#getName()
   * @see #getContext()
   * @generated
   */
  EAttribute getContext_Name();

  /**
   * Returns the meta object for the attribute '{@link fr.lcis.castav.cdl.cDL.Context#isDerived <em>Derived</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Derived</em>'.
   * @see fr.lcis.castav.cdl.cDL.Context#isDerived()
   * @see #getContext()
   * @generated
   */
  EAttribute getContext_Derived();

  /**
   * Returns the meta object for the reference list '{@link fr.lcis.castav.cdl.cDL.Context#getDerives <em>Derives</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Derives</em>'.
   * @see fr.lcis.castav.cdl.cDL.Context#getDerives()
   * @see #getContext()
   * @generated
   */
  EReference getContext_Derives();

  /**
   * Returns the meta object for the reference list '{@link fr.lcis.castav.cdl.cDL.Context#getProviders <em>Providers</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Providers</em>'.
   * @see fr.lcis.castav.cdl.cDL.Context#getProviders()
   * @see #getContext()
   * @generated
   */
  EReference getContext_Providers();

  /**
   * Returns the meta object for the containment reference list '{@link fr.lcis.castav.cdl.cDL.Context#getProperties <em>Properties</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Properties</em>'.
   * @see fr.lcis.castav.cdl.cDL.Context#getProperties()
   * @see #getContext()
   * @generated
   */
  EReference getContext_Properties();

  /**
   * Returns the meta object for the containment reference list '{@link fr.lcis.castav.cdl.cDL.Context#getMappings <em>Mappings</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Mappings</em>'.
   * @see fr.lcis.castav.cdl.cDL.Context#getMappings()
   * @see #getContext()
   * @generated
   */
  EReference getContext_Mappings();

  /**
   * Returns the meta object for class '{@link fr.lcis.castav.cdl.cDL.ContextMapping <em>Context Mapping</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Context Mapping</em>'.
   * @see fr.lcis.castav.cdl.cDL.ContextMapping
   * @generated
   */
  EClass getContextMapping();

  /**
   * Returns the meta object for the reference '{@link fr.lcis.castav.cdl.cDL.ContextMapping#getRef <em>Ref</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Ref</em>'.
   * @see fr.lcis.castav.cdl.cDL.ContextMapping#getRef()
   * @see #getContextMapping()
   * @generated
   */
  EReference getContextMapping_Ref();

  /**
   * Returns the meta object for the containment reference '{@link fr.lcis.castav.cdl.cDL.ContextMapping#getExpression <em>Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Expression</em>'.
   * @see fr.lcis.castav.cdl.cDL.ContextMapping#getExpression()
   * @see #getContextMapping()
   * @generated
   */
  EReference getContextMapping_Expression();

  /**
   * Returns the meta object for class '{@link fr.lcis.castav.cdl.cDL.Providers <em>Providers</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Providers</em>'.
   * @see fr.lcis.castav.cdl.cDL.Providers
   * @generated
   */
  EClass getProviders();

  /**
   * Returns the meta object for the containment reference list '{@link fr.lcis.castav.cdl.cDL.Providers#getProviders <em>Providers</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Providers</em>'.
   * @see fr.lcis.castav.cdl.cDL.Providers#getProviders()
   * @see #getProviders()
   * @generated
   */
  EReference getProviders_Providers();

  /**
   * Returns the meta object for class '{@link fr.lcis.castav.cdl.cDL.Provider <em>Provider</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Provider</em>'.
   * @see fr.lcis.castav.cdl.cDL.Provider
   * @generated
   */
  EClass getProvider();

  /**
   * Returns the meta object for the attribute '{@link fr.lcis.castav.cdl.cDL.Provider#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see fr.lcis.castav.cdl.cDL.Provider#getName()
   * @see #getProvider()
   * @generated
   */
  EAttribute getProvider_Name();

  /**
   * Returns the meta object for class '{@link fr.lcis.castav.cdl.cDL.Property <em>Property</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Property</em>'.
   * @see fr.lcis.castav.cdl.cDL.Property
   * @generated
   */
  EClass getProperty();

  /**
   * Returns the meta object for the attribute '{@link fr.lcis.castav.cdl.cDL.Property#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see fr.lcis.castav.cdl.cDL.Property#getName()
   * @see #getProperty()
   * @generated
   */
  EAttribute getProperty_Name();

  /**
   * Returns the meta object for the containment reference '{@link fr.lcis.castav.cdl.cDL.Property#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Type</em>'.
   * @see fr.lcis.castav.cdl.cDL.Property#getType()
   * @see #getProperty()
   * @generated
   */
  EReference getProperty_Type();

  /**
   * Returns the meta object for class '{@link fr.lcis.castav.cdl.cDL.TypeRef <em>Type Ref</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Type Ref</em>'.
   * @see fr.lcis.castav.cdl.cDL.TypeRef
   * @generated
   */
  EClass getTypeRef();

  /**
   * Returns the meta object for the reference '{@link fr.lcis.castav.cdl.cDL.TypeRef#getRef <em>Ref</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Ref</em>'.
   * @see fr.lcis.castav.cdl.cDL.TypeRef#getRef()
   * @see #getTypeRef()
   * @generated
   */
  EReference getTypeRef_Ref();

  /**
   * Returns the meta object for class '{@link fr.lcis.castav.cdl.cDL.DefinedType <em>Defined Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Defined Type</em>'.
   * @see fr.lcis.castav.cdl.cDL.DefinedType
   * @generated
   */
  EClass getDefinedType();

  /**
   * Returns the meta object for the attribute '{@link fr.lcis.castav.cdl.cDL.DefinedType#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see fr.lcis.castav.cdl.cDL.DefinedType#getName()
   * @see #getDefinedType()
   * @generated
   */
  EAttribute getDefinedType_Name();

  /**
   * Returns the meta object for the containment reference list '{@link fr.lcis.castav.cdl.cDL.DefinedType#getValues <em>Values</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Values</em>'.
   * @see fr.lcis.castav.cdl.cDL.DefinedType#getValues()
   * @see #getDefinedType()
   * @generated
   */
  EReference getDefinedType_Values();

  /**
   * Returns the meta object for class '{@link fr.lcis.castav.cdl.cDL.ContextValue <em>Context Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Context Value</em>'.
   * @see fr.lcis.castav.cdl.cDL.ContextValue
   * @generated
   */
  EClass getContextValue();

  /**
   * Returns the meta object for the attribute '{@link fr.lcis.castav.cdl.cDL.ContextValue#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see fr.lcis.castav.cdl.cDL.ContextValue#getName()
   * @see #getContextValue()
   * @generated
   */
  EAttribute getContextValue_Name();

  /**
   * Returns the meta object for class '{@link fr.lcis.castav.cdl.cDL.SimpleType <em>Simple Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Simple Type</em>'.
   * @see fr.lcis.castav.cdl.cDL.SimpleType
   * @generated
   */
  EClass getSimpleType();

  /**
   * Returns the meta object for class '{@link fr.lcis.castav.cdl.cDL.StringType <em>String Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>String Type</em>'.
   * @see fr.lcis.castav.cdl.cDL.StringType
   * @generated
   */
  EClass getStringType();

  /**
   * Returns the meta object for class '{@link fr.lcis.castav.cdl.cDL.IntegerType <em>Integer Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Integer Type</em>'.
   * @see fr.lcis.castav.cdl.cDL.IntegerType
   * @generated
   */
  EClass getIntegerType();

  /**
   * Returns the meta object for class '{@link fr.lcis.castav.cdl.cDL.BooleanType <em>Boolean Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Boolean Type</em>'.
   * @see fr.lcis.castav.cdl.cDL.BooleanType
   * @generated
   */
  EClass getBooleanType();

  /**
   * Returns the meta object for class '{@link fr.lcis.castav.cdl.cDL.DoubleType <em>Double Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Double Type</em>'.
   * @see fr.lcis.castav.cdl.cDL.DoubleType
   * @generated
   */
  EClass getDoubleType();

  /**
   * Returns the meta object for class '{@link fr.lcis.castav.cdl.cDL.Situation <em>Situation</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Situation</em>'.
   * @see fr.lcis.castav.cdl.cDL.Situation
   * @generated
   */
  EClass getSituation();

  /**
   * Returns the meta object for the attribute '{@link fr.lcis.castav.cdl.cDL.Situation#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see fr.lcis.castav.cdl.cDL.Situation#getName()
   * @see #getSituation()
   * @generated
   */
  EAttribute getSituation_Name();

  /**
   * Returns the meta object for the containment reference list '{@link fr.lcis.castav.cdl.cDL.Situation#getExpression <em>Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Expression</em>'.
   * @see fr.lcis.castav.cdl.cDL.Situation#getExpression()
   * @see #getSituation()
   * @generated
   */
  EReference getSituation_Expression();

  /**
   * Returns the meta object for class '{@link fr.lcis.castav.cdl.cDL.ContextExpression <em>Context Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Context Expression</em>'.
   * @see fr.lcis.castav.cdl.cDL.ContextExpression
   * @generated
   */
  EClass getContextExpression();

  /**
   * Returns the meta object for the reference '{@link fr.lcis.castav.cdl.cDL.ContextExpression#getRef <em>Ref</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Ref</em>'.
   * @see fr.lcis.castav.cdl.cDL.ContextExpression#getRef()
   * @see #getContextExpression()
   * @generated
   */
  EReference getContextExpression_Ref();

  /**
   * Returns the meta object for the containment reference '{@link fr.lcis.castav.cdl.cDL.ContextExpression#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Value</em>'.
   * @see fr.lcis.castav.cdl.cDL.ContextExpression#getValue()
   * @see #getContextExpression()
   * @generated
   */
  EReference getContextExpression_Value();

  /**
   * Returns the meta object for the containment reference '{@link fr.lcis.castav.cdl.cDL.ContextExpression#getExpr <em>Expr</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Expr</em>'.
   * @see fr.lcis.castav.cdl.cDL.ContextExpression#getExpr()
   * @see #getContextExpression()
   * @generated
   */
  EReference getContextExpression_Expr();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  CDLFactory getCDLFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link fr.lcis.castav.cdl.cDL.impl.ContextModelImpl <em>Context Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.lcis.castav.cdl.cDL.impl.ContextModelImpl
     * @see fr.lcis.castav.cdl.cDL.impl.CDLPackageImpl#getContextModel()
     * @generated
     */
    EClass CONTEXT_MODEL = eINSTANCE.getContextModel();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONTEXT_MODEL__NAME = eINSTANCE.getContextModel_Name();

    /**
     * The meta object literal for the '<em><b>Contexts</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONTEXT_MODEL__CONTEXTS = eINSTANCE.getContextModel_Contexts();

    /**
     * The meta object literal for the '<em><b>Providers</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONTEXT_MODEL__PROVIDERS = eINSTANCE.getContextModel_Providers();

    /**
     * The meta object literal for the '<em><b>Situations</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONTEXT_MODEL__SITUATIONS = eINSTANCE.getContextModel_Situations();

    /**
     * The meta object literal for the '<em><b>Types</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONTEXT_MODEL__TYPES = eINSTANCE.getContextModel_Types();

    /**
     * The meta object literal for the '{@link fr.lcis.castav.cdl.cDL.impl.ContextImpl <em>Context</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.lcis.castav.cdl.cDL.impl.ContextImpl
     * @see fr.lcis.castav.cdl.cDL.impl.CDLPackageImpl#getContext()
     * @generated
     */
    EClass CONTEXT = eINSTANCE.getContext();

    /**
     * The meta object literal for the '<em><b>Static</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONTEXT__STATIC = eINSTANCE.getContext_Static();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONTEXT__NAME = eINSTANCE.getContext_Name();

    /**
     * The meta object literal for the '<em><b>Derived</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONTEXT__DERIVED = eINSTANCE.getContext_Derived();

    /**
     * The meta object literal for the '<em><b>Derives</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONTEXT__DERIVES = eINSTANCE.getContext_Derives();

    /**
     * The meta object literal for the '<em><b>Providers</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONTEXT__PROVIDERS = eINSTANCE.getContext_Providers();

    /**
     * The meta object literal for the '<em><b>Properties</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONTEXT__PROPERTIES = eINSTANCE.getContext_Properties();

    /**
     * The meta object literal for the '<em><b>Mappings</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONTEXT__MAPPINGS = eINSTANCE.getContext_Mappings();

    /**
     * The meta object literal for the '{@link fr.lcis.castav.cdl.cDL.impl.ContextMappingImpl <em>Context Mapping</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.lcis.castav.cdl.cDL.impl.ContextMappingImpl
     * @see fr.lcis.castav.cdl.cDL.impl.CDLPackageImpl#getContextMapping()
     * @generated
     */
    EClass CONTEXT_MAPPING = eINSTANCE.getContextMapping();

    /**
     * The meta object literal for the '<em><b>Ref</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONTEXT_MAPPING__REF = eINSTANCE.getContextMapping_Ref();

    /**
     * The meta object literal for the '<em><b>Expression</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONTEXT_MAPPING__EXPRESSION = eINSTANCE.getContextMapping_Expression();

    /**
     * The meta object literal for the '{@link fr.lcis.castav.cdl.cDL.impl.ProvidersImpl <em>Providers</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.lcis.castav.cdl.cDL.impl.ProvidersImpl
     * @see fr.lcis.castav.cdl.cDL.impl.CDLPackageImpl#getProviders()
     * @generated
     */
    EClass PROVIDERS = eINSTANCE.getProviders();

    /**
     * The meta object literal for the '<em><b>Providers</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROVIDERS__PROVIDERS = eINSTANCE.getProviders_Providers();

    /**
     * The meta object literal for the '{@link fr.lcis.castav.cdl.cDL.impl.ProviderImpl <em>Provider</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.lcis.castav.cdl.cDL.impl.ProviderImpl
     * @see fr.lcis.castav.cdl.cDL.impl.CDLPackageImpl#getProvider()
     * @generated
     */
    EClass PROVIDER = eINSTANCE.getProvider();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PROVIDER__NAME = eINSTANCE.getProvider_Name();

    /**
     * The meta object literal for the '{@link fr.lcis.castav.cdl.cDL.impl.PropertyImpl <em>Property</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.lcis.castav.cdl.cDL.impl.PropertyImpl
     * @see fr.lcis.castav.cdl.cDL.impl.CDLPackageImpl#getProperty()
     * @generated
     */
    EClass PROPERTY = eINSTANCE.getProperty();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PROPERTY__NAME = eINSTANCE.getProperty_Name();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROPERTY__TYPE = eINSTANCE.getProperty_Type();

    /**
     * The meta object literal for the '{@link fr.lcis.castav.cdl.cDL.impl.TypeRefImpl <em>Type Ref</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.lcis.castav.cdl.cDL.impl.TypeRefImpl
     * @see fr.lcis.castav.cdl.cDL.impl.CDLPackageImpl#getTypeRef()
     * @generated
     */
    EClass TYPE_REF = eINSTANCE.getTypeRef();

    /**
     * The meta object literal for the '<em><b>Ref</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TYPE_REF__REF = eINSTANCE.getTypeRef_Ref();

    /**
     * The meta object literal for the '{@link fr.lcis.castav.cdl.cDL.impl.DefinedTypeImpl <em>Defined Type</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.lcis.castav.cdl.cDL.impl.DefinedTypeImpl
     * @see fr.lcis.castav.cdl.cDL.impl.CDLPackageImpl#getDefinedType()
     * @generated
     */
    EClass DEFINED_TYPE = eINSTANCE.getDefinedType();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DEFINED_TYPE__NAME = eINSTANCE.getDefinedType_Name();

    /**
     * The meta object literal for the '<em><b>Values</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DEFINED_TYPE__VALUES = eINSTANCE.getDefinedType_Values();

    /**
     * The meta object literal for the '{@link fr.lcis.castav.cdl.cDL.impl.ContextValueImpl <em>Context Value</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.lcis.castav.cdl.cDL.impl.ContextValueImpl
     * @see fr.lcis.castav.cdl.cDL.impl.CDLPackageImpl#getContextValue()
     * @generated
     */
    EClass CONTEXT_VALUE = eINSTANCE.getContextValue();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONTEXT_VALUE__NAME = eINSTANCE.getContextValue_Name();

    /**
     * The meta object literal for the '{@link fr.lcis.castav.cdl.cDL.impl.SimpleTypeImpl <em>Simple Type</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.lcis.castav.cdl.cDL.impl.SimpleTypeImpl
     * @see fr.lcis.castav.cdl.cDL.impl.CDLPackageImpl#getSimpleType()
     * @generated
     */
    EClass SIMPLE_TYPE = eINSTANCE.getSimpleType();

    /**
     * The meta object literal for the '{@link fr.lcis.castav.cdl.cDL.impl.StringTypeImpl <em>String Type</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.lcis.castav.cdl.cDL.impl.StringTypeImpl
     * @see fr.lcis.castav.cdl.cDL.impl.CDLPackageImpl#getStringType()
     * @generated
     */
    EClass STRING_TYPE = eINSTANCE.getStringType();

    /**
     * The meta object literal for the '{@link fr.lcis.castav.cdl.cDL.impl.IntegerTypeImpl <em>Integer Type</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.lcis.castav.cdl.cDL.impl.IntegerTypeImpl
     * @see fr.lcis.castav.cdl.cDL.impl.CDLPackageImpl#getIntegerType()
     * @generated
     */
    EClass INTEGER_TYPE = eINSTANCE.getIntegerType();

    /**
     * The meta object literal for the '{@link fr.lcis.castav.cdl.cDL.impl.BooleanTypeImpl <em>Boolean Type</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.lcis.castav.cdl.cDL.impl.BooleanTypeImpl
     * @see fr.lcis.castav.cdl.cDL.impl.CDLPackageImpl#getBooleanType()
     * @generated
     */
    EClass BOOLEAN_TYPE = eINSTANCE.getBooleanType();

    /**
     * The meta object literal for the '{@link fr.lcis.castav.cdl.cDL.impl.DoubleTypeImpl <em>Double Type</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.lcis.castav.cdl.cDL.impl.DoubleTypeImpl
     * @see fr.lcis.castav.cdl.cDL.impl.CDLPackageImpl#getDoubleType()
     * @generated
     */
    EClass DOUBLE_TYPE = eINSTANCE.getDoubleType();

    /**
     * The meta object literal for the '{@link fr.lcis.castav.cdl.cDL.impl.SituationImpl <em>Situation</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.lcis.castav.cdl.cDL.impl.SituationImpl
     * @see fr.lcis.castav.cdl.cDL.impl.CDLPackageImpl#getSituation()
     * @generated
     */
    EClass SITUATION = eINSTANCE.getSituation();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SITUATION__NAME = eINSTANCE.getSituation_Name();

    /**
     * The meta object literal for the '<em><b>Expression</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SITUATION__EXPRESSION = eINSTANCE.getSituation_Expression();

    /**
     * The meta object literal for the '{@link fr.lcis.castav.cdl.cDL.impl.ContextExpressionImpl <em>Context Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.lcis.castav.cdl.cDL.impl.ContextExpressionImpl
     * @see fr.lcis.castav.cdl.cDL.impl.CDLPackageImpl#getContextExpression()
     * @generated
     */
    EClass CONTEXT_EXPRESSION = eINSTANCE.getContextExpression();

    /**
     * The meta object literal for the '<em><b>Ref</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONTEXT_EXPRESSION__REF = eINSTANCE.getContextExpression_Ref();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONTEXT_EXPRESSION__VALUE = eINSTANCE.getContextExpression_Value();

    /**
     * The meta object literal for the '<em><b>Expr</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONTEXT_EXPRESSION__EXPR = eINSTANCE.getContextExpression_Expr();

  }

} //CDLPackage
