/**
 * generated by Xtext 2.29.0
 */
package fr.lcis.castav.cdl.cDL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Simple Type</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see fr.lcis.castav.cdl.cDL.CDLPackage#getSimpleType()
 * @model
 * @generated
 */
public interface SimpleType extends EObject
{
} // SimpleType
