/*
 * generated by Xtext 2.29.0
 */
package fr.lcis.castav.cdml;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class CDMLRuntimeModule extends AbstractCDMLRuntimeModule {
}
