/**
 * generated by Xtext 2.29.0
 */
package fr.lcis.castav.cdml.cDML;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see fr.lcis.castav.cdml.cDML.CDMLFactory
 * @model kind="package"
 * @generated
 */
public interface CDMLPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "cDML";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.lcis.fr/castav/cdml/CDML";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "cDML";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  CDMLPackage eINSTANCE = fr.lcis.castav.cdml.cDML.impl.CDMLPackageImpl.init();

  /**
   * The meta object id for the '{@link fr.lcis.castav.cdml.cDML.impl.CdmlImpl <em>Cdml</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.lcis.castav.cdml.cDML.impl.CdmlImpl
   * @see fr.lcis.castav.cdml.cDML.impl.CDMLPackageImpl#getCdml()
   * @generated
   */
  int CDML = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CDML__NAME = 0;

  /**
   * The feature id for the '<em><b>Contexts</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CDML__CONTEXTS = 1;

  /**
   * The feature id for the '<em><b>Static Contexts</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CDML__STATIC_CONTEXTS = 2;

  /**
   * The feature id for the '<em><b>Situations</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CDML__SITUATIONS = 3;

  /**
   * The feature id for the '<em><b>Statemachines</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CDML__STATEMACHINES = 4;

  /**
   * The feature id for the '<em><b>Adaptations</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CDML__ADAPTATIONS = 5;

  /**
   * The number of structural features of the '<em>Cdml</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CDML_FEATURE_COUNT = 6;

  /**
   * The meta object id for the '{@link fr.lcis.castav.cdml.cDML.impl.ContextsImpl <em>Contexts</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.lcis.castav.cdml.cDML.impl.ContextsImpl
   * @see fr.lcis.castav.cdml.cDML.impl.CDMLPackageImpl#getContexts()
   * @generated
   */
  int CONTEXTS = 1;

  /**
   * The feature id for the '<em><b>Contexts</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTEXTS__CONTEXTS = 0;

  /**
   * The number of structural features of the '<em>Contexts</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTEXTS_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link fr.lcis.castav.cdml.cDML.impl.ContextImpl <em>Context</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.lcis.castav.cdml.cDML.impl.ContextImpl
   * @see fr.lcis.castav.cdml.cDML.impl.CDMLPackageImpl#getContext()
   * @generated
   */
  int CONTEXT = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTEXT__NAME = 0;

  /**
   * The number of structural features of the '<em>Context</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTEXT_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link fr.lcis.castav.cdml.cDML.impl.StaticContextsImpl <em>Static Contexts</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.lcis.castav.cdml.cDML.impl.StaticContextsImpl
   * @see fr.lcis.castav.cdml.cDML.impl.CDMLPackageImpl#getStaticContexts()
   * @generated
   */
  int STATIC_CONTEXTS = 3;

  /**
   * The feature id for the '<em><b>Static Contexts</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATIC_CONTEXTS__STATIC_CONTEXTS = 0;

  /**
   * The number of structural features of the '<em>Static Contexts</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATIC_CONTEXTS_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link fr.lcis.castav.cdml.cDML.impl.StaticContextImpl <em>Static Context</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.lcis.castav.cdml.cDML.impl.StaticContextImpl
   * @see fr.lcis.castav.cdml.cDML.impl.CDMLPackageImpl#getStaticContext()
   * @generated
   */
  int STATIC_CONTEXT = 4;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATIC_CONTEXT__NAME = 0;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATIC_CONTEXT__VALUE = 1;

  /**
   * The number of structural features of the '<em>Static Context</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATIC_CONTEXT_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link fr.lcis.castav.cdml.cDML.impl.SituationsImpl <em>Situations</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.lcis.castav.cdml.cDML.impl.SituationsImpl
   * @see fr.lcis.castav.cdml.cDML.impl.CDMLPackageImpl#getSituations()
   * @generated
   */
  int SITUATIONS = 5;

  /**
   * The feature id for the '<em><b>Situations</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SITUATIONS__SITUATIONS = 0;

  /**
   * The number of structural features of the '<em>Situations</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SITUATIONS_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link fr.lcis.castav.cdml.cDML.impl.SituationImpl <em>Situation</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.lcis.castav.cdml.cDML.impl.SituationImpl
   * @see fr.lcis.castav.cdml.cDML.impl.CDMLPackageImpl#getSituation()
   * @generated
   */
  int SITUATION = 6;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SITUATION__NAME = 0;

  /**
   * The feature id for the '<em><b>Context</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SITUATION__CONTEXT = 1;

  /**
   * The number of structural features of the '<em>Situation</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SITUATION_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link fr.lcis.castav.cdml.cDML.impl.StatemachineImpl <em>Statemachine</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.lcis.castav.cdml.cDML.impl.StatemachineImpl
   * @see fr.lcis.castav.cdml.cDML.impl.CDMLPackageImpl#getStatemachine()
   * @generated
   */
  int STATEMACHINE = 7;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATEMACHINE__NAME = 0;

  /**
   * The feature id for the '<em><b>Exported</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATEMACHINE__EXPORTED = 1;

  /**
   * The feature id for the '<em><b>Permission</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATEMACHINE__PERMISSION = 2;

  /**
   * The feature id for the '<em><b>States</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATEMACHINE__STATES = 3;

  /**
   * The number of structural features of the '<em>Statemachine</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATEMACHINE_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link fr.lcis.castav.cdml.cDML.impl.StateImpl <em>State</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.lcis.castav.cdml.cDML.impl.StateImpl
   * @see fr.lcis.castav.cdml.cDML.impl.CDMLPackageImpl#getState()
   * @generated
   */
  int STATE = 8;

  /**
   * The feature id for the '<em><b>Transitions</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATE__TRANSITIONS = 0;

  /**
   * The feature id for the '<em><b>Dataflows</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATE__DATAFLOWS = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATE__NAME = 2;

  /**
   * The number of structural features of the '<em>State</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATE_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link fr.lcis.castav.cdml.cDML.impl.AtomicStateImpl <em>Atomic State</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.lcis.castav.cdml.cDML.impl.AtomicStateImpl
   * @see fr.lcis.castav.cdml.cDML.impl.CDMLPackageImpl#getAtomicState()
   * @generated
   */
  int ATOMIC_STATE = 9;

  /**
   * The feature id for the '<em><b>Transitions</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATOMIC_STATE__TRANSITIONS = STATE__TRANSITIONS;

  /**
   * The feature id for the '<em><b>Dataflows</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATOMIC_STATE__DATAFLOWS = STATE__DATAFLOWS;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATOMIC_STATE__NAME = STATE__NAME;

  /**
   * The feature id for the '<em><b>Context Aware</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATOMIC_STATE__CONTEXT_AWARE = STATE_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Contexts</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATOMIC_STATE__CONTEXTS = STATE_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Atomic State</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATOMIC_STATE_FEATURE_COUNT = STATE_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link fr.lcis.castav.cdml.cDML.impl.SuperStateImpl <em>Super State</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.lcis.castav.cdml.cDML.impl.SuperStateImpl
   * @see fr.lcis.castav.cdml.cDML.impl.CDMLPackageImpl#getSuperState()
   * @generated
   */
  int SUPER_STATE = 10;

  /**
   * The feature id for the '<em><b>Transitions</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SUPER_STATE__TRANSITIONS = STATE__TRANSITIONS;

  /**
   * The feature id for the '<em><b>Dataflows</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SUPER_STATE__DATAFLOWS = STATE__DATAFLOWS;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SUPER_STATE__NAME = STATE__NAME;

  /**
   * The feature id for the '<em><b>Abstracts</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SUPER_STATE__ABSTRACTS = STATE_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Super State</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SUPER_STATE_FEATURE_COUNT = STATE_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link fr.lcis.castav.cdml.cDML.impl.TransitionImpl <em>Transition</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.lcis.castav.cdml.cDML.impl.TransitionImpl
   * @see fr.lcis.castav.cdml.cDML.impl.CDMLPackageImpl#getTransition()
   * @generated
   */
  int TRANSITION = 11;

  /**
   * The feature id for the '<em><b>On</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRANSITION__ON = 0;

  /**
   * The feature id for the '<em><b>External</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRANSITION__EXTERNAL = 1;

  /**
   * The feature id for the '<em><b>Target</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRANSITION__TARGET = 2;

  /**
   * The number of structural features of the '<em>Transition</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRANSITION_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link fr.lcis.castav.cdml.cDML.impl.EventImpl <em>Event</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.lcis.castav.cdml.cDML.impl.EventImpl
   * @see fr.lcis.castav.cdml.cDML.impl.CDMLPackageImpl#getEvent()
   * @generated
   */
  int EVENT = 12;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EVENT__NAME = 0;

  /**
   * The number of structural features of the '<em>Event</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EVENT_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link fr.lcis.castav.cdml.cDML.impl.PermissionImpl <em>Permission</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.lcis.castav.cdml.cDML.impl.PermissionImpl
   * @see fr.lcis.castav.cdml.cDML.impl.CDMLPackageImpl#getPermission()
   * @generated
   */
  int PERMISSION = 13;

  /**
   * The feature id for the '<em><b>Normal</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PERMISSION__NORMAL = 0;

  /**
   * The feature id for the '<em><b>Permission Values</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PERMISSION__PERMISSION_VALUES = 1;

  /**
   * The feature id for the '<em><b>Dangerous</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PERMISSION__DANGEROUS = 2;

  /**
   * The feature id for the '<em><b>Signature</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PERMISSION__SIGNATURE = 3;

  /**
   * The feature id for the '<em><b>Signature Or System</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PERMISSION__SIGNATURE_OR_SYSTEM = 4;

  /**
   * The number of structural features of the '<em>Permission</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PERMISSION_FEATURE_COUNT = 5;

  /**
   * The meta object id for the '{@link fr.lcis.castav.cdml.cDML.impl.PermissionValueImpl <em>Permission Value</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.lcis.castav.cdml.cDML.impl.PermissionValueImpl
   * @see fr.lcis.castav.cdml.cDML.impl.CDMLPackageImpl#getPermissionValue()
   * @generated
   */
  int PERMISSION_VALUE = 14;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PERMISSION_VALUE__NAME = 0;

  /**
   * The number of structural features of the '<em>Permission Value</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PERMISSION_VALUE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link fr.lcis.castav.cdml.cDML.impl.DataFlowImpl <em>Data Flow</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.lcis.castav.cdml.cDML.impl.DataFlowImpl
   * @see fr.lcis.castav.cdml.cDML.impl.CDMLPackageImpl#getDataFlow()
   * @generated
   */
  int DATA_FLOW = 15;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DATA_FLOW__NAME = 0;

  /**
   * The number of structural features of the '<em>Data Flow</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DATA_FLOW_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link fr.lcis.castav.cdml.cDML.impl.SinkImpl <em>Sink</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.lcis.castav.cdml.cDML.impl.SinkImpl
   * @see fr.lcis.castav.cdml.cDML.impl.CDMLPackageImpl#getSink()
   * @generated
   */
  int SINK = 16;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SINK__NAME = DATA_FLOW__NAME;

  /**
   * The feature id for the '<em><b>Parameters</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SINK__PARAMETERS = DATA_FLOW_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Sink</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SINK_FEATURE_COUNT = DATA_FLOW_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link fr.lcis.castav.cdml.cDML.impl.ParameterImpl <em>Parameter</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.lcis.castav.cdml.cDML.impl.ParameterImpl
   * @see fr.lcis.castav.cdml.cDML.impl.CDMLPackageImpl#getParameter()
   * @generated
   */
  int PARAMETER = 17;

  /**
   * The feature id for the '<em><b>Wildcard</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAMETER__WILDCARD = 0;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAMETER__VALUE = 1;

  /**
   * The feature id for the '<em><b>Source</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAMETER__SOURCE = 2;

  /**
   * The feature id for the '<em><b>Origin</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAMETER__ORIGIN = 3;

  /**
   * The number of structural features of the '<em>Parameter</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAMETER_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link fr.lcis.castav.cdml.cDML.impl.SourceImpl <em>Source</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.lcis.castav.cdml.cDML.impl.SourceImpl
   * @see fr.lcis.castav.cdml.cDML.impl.CDMLPackageImpl#getSource()
   * @generated
   */
  int SOURCE = 18;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SOURCE__NAME = DATA_FLOW__NAME;

  /**
   * The feature id for the '<em><b>Input</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SOURCE__INPUT = DATA_FLOW_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Source</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SOURCE_FEATURE_COUNT = DATA_FLOW_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link fr.lcis.castav.cdml.cDML.impl.AdaptationImpl <em>Adaptation</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.lcis.castav.cdml.cDML.impl.AdaptationImpl
   * @see fr.lcis.castav.cdml.cDML.impl.CDMLPackageImpl#getAdaptation()
   * @generated
   */
  int ADAPTATION = 19;

  /**
   * The feature id for the '<em><b>Situations</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ADAPTATION__SITUATIONS = 0;

  /**
   * The feature id for the '<em><b>State</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ADAPTATION__STATE = 1;

  /**
   * The feature id for the '<em><b>States</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ADAPTATION__STATES = 2;

  /**
   * The number of structural features of the '<em>Adaptation</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ADAPTATION_FEATURE_COUNT = 3;


  /**
   * Returns the meta object for class '{@link fr.lcis.castav.cdml.cDML.Cdml <em>Cdml</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Cdml</em>'.
   * @see fr.lcis.castav.cdml.cDML.Cdml
   * @generated
   */
  EClass getCdml();

  /**
   * Returns the meta object for the attribute '{@link fr.lcis.castav.cdml.cDML.Cdml#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see fr.lcis.castav.cdml.cDML.Cdml#getName()
   * @see #getCdml()
   * @generated
   */
  EAttribute getCdml_Name();

  /**
   * Returns the meta object for the containment reference list '{@link fr.lcis.castav.cdml.cDML.Cdml#getContexts <em>Contexts</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Contexts</em>'.
   * @see fr.lcis.castav.cdml.cDML.Cdml#getContexts()
   * @see #getCdml()
   * @generated
   */
  EReference getCdml_Contexts();

  /**
   * Returns the meta object for the containment reference list '{@link fr.lcis.castav.cdml.cDML.Cdml#getStaticContexts <em>Static Contexts</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Static Contexts</em>'.
   * @see fr.lcis.castav.cdml.cDML.Cdml#getStaticContexts()
   * @see #getCdml()
   * @generated
   */
  EReference getCdml_StaticContexts();

  /**
   * Returns the meta object for the containment reference list '{@link fr.lcis.castav.cdml.cDML.Cdml#getSituations <em>Situations</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Situations</em>'.
   * @see fr.lcis.castav.cdml.cDML.Cdml#getSituations()
   * @see #getCdml()
   * @generated
   */
  EReference getCdml_Situations();

  /**
   * Returns the meta object for the containment reference list '{@link fr.lcis.castav.cdml.cDML.Cdml#getStatemachines <em>Statemachines</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Statemachines</em>'.
   * @see fr.lcis.castav.cdml.cDML.Cdml#getStatemachines()
   * @see #getCdml()
   * @generated
   */
  EReference getCdml_Statemachines();

  /**
   * Returns the meta object for the containment reference list '{@link fr.lcis.castav.cdml.cDML.Cdml#getAdaptations <em>Adaptations</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Adaptations</em>'.
   * @see fr.lcis.castav.cdml.cDML.Cdml#getAdaptations()
   * @see #getCdml()
   * @generated
   */
  EReference getCdml_Adaptations();

  /**
   * Returns the meta object for class '{@link fr.lcis.castav.cdml.cDML.Contexts <em>Contexts</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Contexts</em>'.
   * @see fr.lcis.castav.cdml.cDML.Contexts
   * @generated
   */
  EClass getContexts();

  /**
   * Returns the meta object for the containment reference list '{@link fr.lcis.castav.cdml.cDML.Contexts#getContexts <em>Contexts</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Contexts</em>'.
   * @see fr.lcis.castav.cdml.cDML.Contexts#getContexts()
   * @see #getContexts()
   * @generated
   */
  EReference getContexts_Contexts();

  /**
   * Returns the meta object for class '{@link fr.lcis.castav.cdml.cDML.Context <em>Context</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Context</em>'.
   * @see fr.lcis.castav.cdml.cDML.Context
   * @generated
   */
  EClass getContext();

  /**
   * Returns the meta object for the attribute '{@link fr.lcis.castav.cdml.cDML.Context#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see fr.lcis.castav.cdml.cDML.Context#getName()
   * @see #getContext()
   * @generated
   */
  EAttribute getContext_Name();

  /**
   * Returns the meta object for class '{@link fr.lcis.castav.cdml.cDML.StaticContexts <em>Static Contexts</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Static Contexts</em>'.
   * @see fr.lcis.castav.cdml.cDML.StaticContexts
   * @generated
   */
  EClass getStaticContexts();

  /**
   * Returns the meta object for the containment reference list '{@link fr.lcis.castav.cdml.cDML.StaticContexts#getStaticContexts <em>Static Contexts</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Static Contexts</em>'.
   * @see fr.lcis.castav.cdml.cDML.StaticContexts#getStaticContexts()
   * @see #getStaticContexts()
   * @generated
   */
  EReference getStaticContexts_StaticContexts();

  /**
   * Returns the meta object for class '{@link fr.lcis.castav.cdml.cDML.StaticContext <em>Static Context</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Static Context</em>'.
   * @see fr.lcis.castav.cdml.cDML.StaticContext
   * @generated
   */
  EClass getStaticContext();

  /**
   * Returns the meta object for the attribute '{@link fr.lcis.castav.cdml.cDML.StaticContext#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see fr.lcis.castav.cdml.cDML.StaticContext#getName()
   * @see #getStaticContext()
   * @generated
   */
  EAttribute getStaticContext_Name();

  /**
   * Returns the meta object for the attribute '{@link fr.lcis.castav.cdml.cDML.StaticContext#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see fr.lcis.castav.cdml.cDML.StaticContext#getValue()
   * @see #getStaticContext()
   * @generated
   */
  EAttribute getStaticContext_Value();

  /**
   * Returns the meta object for class '{@link fr.lcis.castav.cdml.cDML.Situations <em>Situations</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Situations</em>'.
   * @see fr.lcis.castav.cdml.cDML.Situations
   * @generated
   */
  EClass getSituations();

  /**
   * Returns the meta object for the containment reference list '{@link fr.lcis.castav.cdml.cDML.Situations#getSituations <em>Situations</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Situations</em>'.
   * @see fr.lcis.castav.cdml.cDML.Situations#getSituations()
   * @see #getSituations()
   * @generated
   */
  EReference getSituations_Situations();

  /**
   * Returns the meta object for class '{@link fr.lcis.castav.cdml.cDML.Situation <em>Situation</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Situation</em>'.
   * @see fr.lcis.castav.cdml.cDML.Situation
   * @generated
   */
  EClass getSituation();

  /**
   * Returns the meta object for the attribute '{@link fr.lcis.castav.cdml.cDML.Situation#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see fr.lcis.castav.cdml.cDML.Situation#getName()
   * @see #getSituation()
   * @generated
   */
  EAttribute getSituation_Name();

  /**
   * Returns the meta object for the reference '{@link fr.lcis.castav.cdml.cDML.Situation#getContext <em>Context</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Context</em>'.
   * @see fr.lcis.castav.cdml.cDML.Situation#getContext()
   * @see #getSituation()
   * @generated
   */
  EReference getSituation_Context();

  /**
   * Returns the meta object for class '{@link fr.lcis.castav.cdml.cDML.Statemachine <em>Statemachine</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Statemachine</em>'.
   * @see fr.lcis.castav.cdml.cDML.Statemachine
   * @generated
   */
  EClass getStatemachine();

  /**
   * Returns the meta object for the attribute '{@link fr.lcis.castav.cdml.cDML.Statemachine#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see fr.lcis.castav.cdml.cDML.Statemachine#getName()
   * @see #getStatemachine()
   * @generated
   */
  EAttribute getStatemachine_Name();

  /**
   * Returns the meta object for the attribute '{@link fr.lcis.castav.cdml.cDML.Statemachine#isExported <em>Exported</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Exported</em>'.
   * @see fr.lcis.castav.cdml.cDML.Statemachine#isExported()
   * @see #getStatemachine()
   * @generated
   */
  EAttribute getStatemachine_Exported();

  /**
   * Returns the meta object for the containment reference '{@link fr.lcis.castav.cdml.cDML.Statemachine#getPermission <em>Permission</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Permission</em>'.
   * @see fr.lcis.castav.cdml.cDML.Statemachine#getPermission()
   * @see #getStatemachine()
   * @generated
   */
  EReference getStatemachine_Permission();

  /**
   * Returns the meta object for the containment reference list '{@link fr.lcis.castav.cdml.cDML.Statemachine#getStates <em>States</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>States</em>'.
   * @see fr.lcis.castav.cdml.cDML.Statemachine#getStates()
   * @see #getStatemachine()
   * @generated
   */
  EReference getStatemachine_States();

  /**
   * Returns the meta object for class '{@link fr.lcis.castav.cdml.cDML.State <em>State</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>State</em>'.
   * @see fr.lcis.castav.cdml.cDML.State
   * @generated
   */
  EClass getState();

  /**
   * Returns the meta object for the containment reference list '{@link fr.lcis.castav.cdml.cDML.State#getTransitions <em>Transitions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Transitions</em>'.
   * @see fr.lcis.castav.cdml.cDML.State#getTransitions()
   * @see #getState()
   * @generated
   */
  EReference getState_Transitions();

  /**
   * Returns the meta object for the containment reference list '{@link fr.lcis.castav.cdml.cDML.State#getDataflows <em>Dataflows</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Dataflows</em>'.
   * @see fr.lcis.castav.cdml.cDML.State#getDataflows()
   * @see #getState()
   * @generated
   */
  EReference getState_Dataflows();

  /**
   * Returns the meta object for the attribute '{@link fr.lcis.castav.cdml.cDML.State#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see fr.lcis.castav.cdml.cDML.State#getName()
   * @see #getState()
   * @generated
   */
  EAttribute getState_Name();

  /**
   * Returns the meta object for class '{@link fr.lcis.castav.cdml.cDML.AtomicState <em>Atomic State</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Atomic State</em>'.
   * @see fr.lcis.castav.cdml.cDML.AtomicState
   * @generated
   */
  EClass getAtomicState();

  /**
   * Returns the meta object for the attribute '{@link fr.lcis.castav.cdml.cDML.AtomicState#isContextAware <em>Context Aware</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Context Aware</em>'.
   * @see fr.lcis.castav.cdml.cDML.AtomicState#isContextAware()
   * @see #getAtomicState()
   * @generated
   */
  EAttribute getAtomicState_ContextAware();

  /**
   * Returns the meta object for the reference list '{@link fr.lcis.castav.cdml.cDML.AtomicState#getContexts <em>Contexts</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Contexts</em>'.
   * @see fr.lcis.castav.cdml.cDML.AtomicState#getContexts()
   * @see #getAtomicState()
   * @generated
   */
  EReference getAtomicState_Contexts();

  /**
   * Returns the meta object for class '{@link fr.lcis.castav.cdml.cDML.SuperState <em>Super State</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Super State</em>'.
   * @see fr.lcis.castav.cdml.cDML.SuperState
   * @generated
   */
  EClass getSuperState();

  /**
   * Returns the meta object for the reference '{@link fr.lcis.castav.cdml.cDML.SuperState#getAbstracts <em>Abstracts</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Abstracts</em>'.
   * @see fr.lcis.castav.cdml.cDML.SuperState#getAbstracts()
   * @see #getSuperState()
   * @generated
   */
  EReference getSuperState_Abstracts();

  /**
   * Returns the meta object for class '{@link fr.lcis.castav.cdml.cDML.Transition <em>Transition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Transition</em>'.
   * @see fr.lcis.castav.cdml.cDML.Transition
   * @generated
   */
  EClass getTransition();

  /**
   * Returns the meta object for the containment reference '{@link fr.lcis.castav.cdml.cDML.Transition#getOn <em>On</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>On</em>'.
   * @see fr.lcis.castav.cdml.cDML.Transition#getOn()
   * @see #getTransition()
   * @generated
   */
  EReference getTransition_On();

  /**
   * Returns the meta object for the attribute '{@link fr.lcis.castav.cdml.cDML.Transition#isExternal <em>External</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>External</em>'.
   * @see fr.lcis.castav.cdml.cDML.Transition#isExternal()
   * @see #getTransition()
   * @generated
   */
  EAttribute getTransition_External();

  /**
   * Returns the meta object for the reference '{@link fr.lcis.castav.cdml.cDML.Transition#getTarget <em>Target</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Target</em>'.
   * @see fr.lcis.castav.cdml.cDML.Transition#getTarget()
   * @see #getTransition()
   * @generated
   */
  EReference getTransition_Target();

  /**
   * Returns the meta object for class '{@link fr.lcis.castav.cdml.cDML.Event <em>Event</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Event</em>'.
   * @see fr.lcis.castav.cdml.cDML.Event
   * @generated
   */
  EClass getEvent();

  /**
   * Returns the meta object for the attribute '{@link fr.lcis.castav.cdml.cDML.Event#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see fr.lcis.castav.cdml.cDML.Event#getName()
   * @see #getEvent()
   * @generated
   */
  EAttribute getEvent_Name();

  /**
   * Returns the meta object for class '{@link fr.lcis.castav.cdml.cDML.Permission <em>Permission</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Permission</em>'.
   * @see fr.lcis.castav.cdml.cDML.Permission
   * @generated
   */
  EClass getPermission();

  /**
   * Returns the meta object for the attribute '{@link fr.lcis.castav.cdml.cDML.Permission#isNormal <em>Normal</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Normal</em>'.
   * @see fr.lcis.castav.cdml.cDML.Permission#isNormal()
   * @see #getPermission()
   * @generated
   */
  EAttribute getPermission_Normal();

  /**
   * Returns the meta object for the containment reference list '{@link fr.lcis.castav.cdml.cDML.Permission#getPermissionValues <em>Permission Values</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Permission Values</em>'.
   * @see fr.lcis.castav.cdml.cDML.Permission#getPermissionValues()
   * @see #getPermission()
   * @generated
   */
  EReference getPermission_PermissionValues();

  /**
   * Returns the meta object for the attribute '{@link fr.lcis.castav.cdml.cDML.Permission#isDangerous <em>Dangerous</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Dangerous</em>'.
   * @see fr.lcis.castav.cdml.cDML.Permission#isDangerous()
   * @see #getPermission()
   * @generated
   */
  EAttribute getPermission_Dangerous();

  /**
   * Returns the meta object for the attribute '{@link fr.lcis.castav.cdml.cDML.Permission#isSignature <em>Signature</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Signature</em>'.
   * @see fr.lcis.castav.cdml.cDML.Permission#isSignature()
   * @see #getPermission()
   * @generated
   */
  EAttribute getPermission_Signature();

  /**
   * Returns the meta object for the attribute '{@link fr.lcis.castav.cdml.cDML.Permission#isSignatureOrSystem <em>Signature Or System</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Signature Or System</em>'.
   * @see fr.lcis.castav.cdml.cDML.Permission#isSignatureOrSystem()
   * @see #getPermission()
   * @generated
   */
  EAttribute getPermission_SignatureOrSystem();

  /**
   * Returns the meta object for class '{@link fr.lcis.castav.cdml.cDML.PermissionValue <em>Permission Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Permission Value</em>'.
   * @see fr.lcis.castav.cdml.cDML.PermissionValue
   * @generated
   */
  EClass getPermissionValue();

  /**
   * Returns the meta object for the attribute '{@link fr.lcis.castav.cdml.cDML.PermissionValue#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see fr.lcis.castav.cdml.cDML.PermissionValue#getName()
   * @see #getPermissionValue()
   * @generated
   */
  EAttribute getPermissionValue_Name();

  /**
   * Returns the meta object for class '{@link fr.lcis.castav.cdml.cDML.DataFlow <em>Data Flow</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Data Flow</em>'.
   * @see fr.lcis.castav.cdml.cDML.DataFlow
   * @generated
   */
  EClass getDataFlow();

  /**
   * Returns the meta object for the attribute '{@link fr.lcis.castav.cdml.cDML.DataFlow#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see fr.lcis.castav.cdml.cDML.DataFlow#getName()
   * @see #getDataFlow()
   * @generated
   */
  EAttribute getDataFlow_Name();

  /**
   * Returns the meta object for class '{@link fr.lcis.castav.cdml.cDML.Sink <em>Sink</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Sink</em>'.
   * @see fr.lcis.castav.cdml.cDML.Sink
   * @generated
   */
  EClass getSink();

  /**
   * Returns the meta object for the containment reference list '{@link fr.lcis.castav.cdml.cDML.Sink#getParameters <em>Parameters</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Parameters</em>'.
   * @see fr.lcis.castav.cdml.cDML.Sink#getParameters()
   * @see #getSink()
   * @generated
   */
  EReference getSink_Parameters();

  /**
   * Returns the meta object for class '{@link fr.lcis.castav.cdml.cDML.Parameter <em>Parameter</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Parameter</em>'.
   * @see fr.lcis.castav.cdml.cDML.Parameter
   * @generated
   */
  EClass getParameter();

  /**
   * Returns the meta object for the attribute '{@link fr.lcis.castav.cdml.cDML.Parameter#isWildcard <em>Wildcard</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Wildcard</em>'.
   * @see fr.lcis.castav.cdml.cDML.Parameter#isWildcard()
   * @see #getParameter()
   * @generated
   */
  EAttribute getParameter_Wildcard();

  /**
   * Returns the meta object for the attribute '{@link fr.lcis.castav.cdml.cDML.Parameter#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see fr.lcis.castav.cdml.cDML.Parameter#getValue()
   * @see #getParameter()
   * @generated
   */
  EAttribute getParameter_Value();

  /**
   * Returns the meta object for the attribute '{@link fr.lcis.castav.cdml.cDML.Parameter#isSource <em>Source</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Source</em>'.
   * @see fr.lcis.castav.cdml.cDML.Parameter#isSource()
   * @see #getParameter()
   * @generated
   */
  EAttribute getParameter_Source();

  /**
   * Returns the meta object for the reference '{@link fr.lcis.castav.cdml.cDML.Parameter#getOrigin <em>Origin</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Origin</em>'.
   * @see fr.lcis.castav.cdml.cDML.Parameter#getOrigin()
   * @see #getParameter()
   * @generated
   */
  EReference getParameter_Origin();

  /**
   * Returns the meta object for class '{@link fr.lcis.castav.cdml.cDML.Source <em>Source</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Source</em>'.
   * @see fr.lcis.castav.cdml.cDML.Source
   * @generated
   */
  EClass getSource();

  /**
   * Returns the meta object for the attribute '{@link fr.lcis.castav.cdml.cDML.Source#isInput <em>Input</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Input</em>'.
   * @see fr.lcis.castav.cdml.cDML.Source#isInput()
   * @see #getSource()
   * @generated
   */
  EAttribute getSource_Input();

  /**
   * Returns the meta object for class '{@link fr.lcis.castav.cdml.cDML.Adaptation <em>Adaptation</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Adaptation</em>'.
   * @see fr.lcis.castav.cdml.cDML.Adaptation
   * @generated
   */
  EClass getAdaptation();

  /**
   * Returns the meta object for the reference list '{@link fr.lcis.castav.cdml.cDML.Adaptation#getSituations <em>Situations</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Situations</em>'.
   * @see fr.lcis.castav.cdml.cDML.Adaptation#getSituations()
   * @see #getAdaptation()
   * @generated
   */
  EReference getAdaptation_Situations();

  /**
   * Returns the meta object for the reference '{@link fr.lcis.castav.cdml.cDML.Adaptation#getState <em>State</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>State</em>'.
   * @see fr.lcis.castav.cdml.cDML.Adaptation#getState()
   * @see #getAdaptation()
   * @generated
   */
  EReference getAdaptation_State();

  /**
   * Returns the meta object for the containment reference list '{@link fr.lcis.castav.cdml.cDML.Adaptation#getStates <em>States</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>States</em>'.
   * @see fr.lcis.castav.cdml.cDML.Adaptation#getStates()
   * @see #getAdaptation()
   * @generated
   */
  EReference getAdaptation_States();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  CDMLFactory getCDMLFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link fr.lcis.castav.cdml.cDML.impl.CdmlImpl <em>Cdml</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.lcis.castav.cdml.cDML.impl.CdmlImpl
     * @see fr.lcis.castav.cdml.cDML.impl.CDMLPackageImpl#getCdml()
     * @generated
     */
    EClass CDML = eINSTANCE.getCdml();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CDML__NAME = eINSTANCE.getCdml_Name();

    /**
     * The meta object literal for the '<em><b>Contexts</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CDML__CONTEXTS = eINSTANCE.getCdml_Contexts();

    /**
     * The meta object literal for the '<em><b>Static Contexts</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CDML__STATIC_CONTEXTS = eINSTANCE.getCdml_StaticContexts();

    /**
     * The meta object literal for the '<em><b>Situations</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CDML__SITUATIONS = eINSTANCE.getCdml_Situations();

    /**
     * The meta object literal for the '<em><b>Statemachines</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CDML__STATEMACHINES = eINSTANCE.getCdml_Statemachines();

    /**
     * The meta object literal for the '<em><b>Adaptations</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CDML__ADAPTATIONS = eINSTANCE.getCdml_Adaptations();

    /**
     * The meta object literal for the '{@link fr.lcis.castav.cdml.cDML.impl.ContextsImpl <em>Contexts</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.lcis.castav.cdml.cDML.impl.ContextsImpl
     * @see fr.lcis.castav.cdml.cDML.impl.CDMLPackageImpl#getContexts()
     * @generated
     */
    EClass CONTEXTS = eINSTANCE.getContexts();

    /**
     * The meta object literal for the '<em><b>Contexts</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONTEXTS__CONTEXTS = eINSTANCE.getContexts_Contexts();

    /**
     * The meta object literal for the '{@link fr.lcis.castav.cdml.cDML.impl.ContextImpl <em>Context</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.lcis.castav.cdml.cDML.impl.ContextImpl
     * @see fr.lcis.castav.cdml.cDML.impl.CDMLPackageImpl#getContext()
     * @generated
     */
    EClass CONTEXT = eINSTANCE.getContext();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONTEXT__NAME = eINSTANCE.getContext_Name();

    /**
     * The meta object literal for the '{@link fr.lcis.castav.cdml.cDML.impl.StaticContextsImpl <em>Static Contexts</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.lcis.castav.cdml.cDML.impl.StaticContextsImpl
     * @see fr.lcis.castav.cdml.cDML.impl.CDMLPackageImpl#getStaticContexts()
     * @generated
     */
    EClass STATIC_CONTEXTS = eINSTANCE.getStaticContexts();

    /**
     * The meta object literal for the '<em><b>Static Contexts</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STATIC_CONTEXTS__STATIC_CONTEXTS = eINSTANCE.getStaticContexts_StaticContexts();

    /**
     * The meta object literal for the '{@link fr.lcis.castav.cdml.cDML.impl.StaticContextImpl <em>Static Context</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.lcis.castav.cdml.cDML.impl.StaticContextImpl
     * @see fr.lcis.castav.cdml.cDML.impl.CDMLPackageImpl#getStaticContext()
     * @generated
     */
    EClass STATIC_CONTEXT = eINSTANCE.getStaticContext();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STATIC_CONTEXT__NAME = eINSTANCE.getStaticContext_Name();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STATIC_CONTEXT__VALUE = eINSTANCE.getStaticContext_Value();

    /**
     * The meta object literal for the '{@link fr.lcis.castav.cdml.cDML.impl.SituationsImpl <em>Situations</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.lcis.castav.cdml.cDML.impl.SituationsImpl
     * @see fr.lcis.castav.cdml.cDML.impl.CDMLPackageImpl#getSituations()
     * @generated
     */
    EClass SITUATIONS = eINSTANCE.getSituations();

    /**
     * The meta object literal for the '<em><b>Situations</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SITUATIONS__SITUATIONS = eINSTANCE.getSituations_Situations();

    /**
     * The meta object literal for the '{@link fr.lcis.castav.cdml.cDML.impl.SituationImpl <em>Situation</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.lcis.castav.cdml.cDML.impl.SituationImpl
     * @see fr.lcis.castav.cdml.cDML.impl.CDMLPackageImpl#getSituation()
     * @generated
     */
    EClass SITUATION = eINSTANCE.getSituation();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SITUATION__NAME = eINSTANCE.getSituation_Name();

    /**
     * The meta object literal for the '<em><b>Context</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SITUATION__CONTEXT = eINSTANCE.getSituation_Context();

    /**
     * The meta object literal for the '{@link fr.lcis.castav.cdml.cDML.impl.StatemachineImpl <em>Statemachine</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.lcis.castav.cdml.cDML.impl.StatemachineImpl
     * @see fr.lcis.castav.cdml.cDML.impl.CDMLPackageImpl#getStatemachine()
     * @generated
     */
    EClass STATEMACHINE = eINSTANCE.getStatemachine();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STATEMACHINE__NAME = eINSTANCE.getStatemachine_Name();

    /**
     * The meta object literal for the '<em><b>Exported</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STATEMACHINE__EXPORTED = eINSTANCE.getStatemachine_Exported();

    /**
     * The meta object literal for the '<em><b>Permission</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STATEMACHINE__PERMISSION = eINSTANCE.getStatemachine_Permission();

    /**
     * The meta object literal for the '<em><b>States</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STATEMACHINE__STATES = eINSTANCE.getStatemachine_States();

    /**
     * The meta object literal for the '{@link fr.lcis.castav.cdml.cDML.impl.StateImpl <em>State</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.lcis.castav.cdml.cDML.impl.StateImpl
     * @see fr.lcis.castav.cdml.cDML.impl.CDMLPackageImpl#getState()
     * @generated
     */
    EClass STATE = eINSTANCE.getState();

    /**
     * The meta object literal for the '<em><b>Transitions</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STATE__TRANSITIONS = eINSTANCE.getState_Transitions();

    /**
     * The meta object literal for the '<em><b>Dataflows</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STATE__DATAFLOWS = eINSTANCE.getState_Dataflows();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STATE__NAME = eINSTANCE.getState_Name();

    /**
     * The meta object literal for the '{@link fr.lcis.castav.cdml.cDML.impl.AtomicStateImpl <em>Atomic State</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.lcis.castav.cdml.cDML.impl.AtomicStateImpl
     * @see fr.lcis.castav.cdml.cDML.impl.CDMLPackageImpl#getAtomicState()
     * @generated
     */
    EClass ATOMIC_STATE = eINSTANCE.getAtomicState();

    /**
     * The meta object literal for the '<em><b>Context Aware</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ATOMIC_STATE__CONTEXT_AWARE = eINSTANCE.getAtomicState_ContextAware();

    /**
     * The meta object literal for the '<em><b>Contexts</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ATOMIC_STATE__CONTEXTS = eINSTANCE.getAtomicState_Contexts();

    /**
     * The meta object literal for the '{@link fr.lcis.castav.cdml.cDML.impl.SuperStateImpl <em>Super State</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.lcis.castav.cdml.cDML.impl.SuperStateImpl
     * @see fr.lcis.castav.cdml.cDML.impl.CDMLPackageImpl#getSuperState()
     * @generated
     */
    EClass SUPER_STATE = eINSTANCE.getSuperState();

    /**
     * The meta object literal for the '<em><b>Abstracts</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SUPER_STATE__ABSTRACTS = eINSTANCE.getSuperState_Abstracts();

    /**
     * The meta object literal for the '{@link fr.lcis.castav.cdml.cDML.impl.TransitionImpl <em>Transition</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.lcis.castav.cdml.cDML.impl.TransitionImpl
     * @see fr.lcis.castav.cdml.cDML.impl.CDMLPackageImpl#getTransition()
     * @generated
     */
    EClass TRANSITION = eINSTANCE.getTransition();

    /**
     * The meta object literal for the '<em><b>On</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TRANSITION__ON = eINSTANCE.getTransition_On();

    /**
     * The meta object literal for the '<em><b>External</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TRANSITION__EXTERNAL = eINSTANCE.getTransition_External();

    /**
     * The meta object literal for the '<em><b>Target</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TRANSITION__TARGET = eINSTANCE.getTransition_Target();

    /**
     * The meta object literal for the '{@link fr.lcis.castav.cdml.cDML.impl.EventImpl <em>Event</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.lcis.castav.cdml.cDML.impl.EventImpl
     * @see fr.lcis.castav.cdml.cDML.impl.CDMLPackageImpl#getEvent()
     * @generated
     */
    EClass EVENT = eINSTANCE.getEvent();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EVENT__NAME = eINSTANCE.getEvent_Name();

    /**
     * The meta object literal for the '{@link fr.lcis.castav.cdml.cDML.impl.PermissionImpl <em>Permission</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.lcis.castav.cdml.cDML.impl.PermissionImpl
     * @see fr.lcis.castav.cdml.cDML.impl.CDMLPackageImpl#getPermission()
     * @generated
     */
    EClass PERMISSION = eINSTANCE.getPermission();

    /**
     * The meta object literal for the '<em><b>Normal</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PERMISSION__NORMAL = eINSTANCE.getPermission_Normal();

    /**
     * The meta object literal for the '<em><b>Permission Values</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PERMISSION__PERMISSION_VALUES = eINSTANCE.getPermission_PermissionValues();

    /**
     * The meta object literal for the '<em><b>Dangerous</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PERMISSION__DANGEROUS = eINSTANCE.getPermission_Dangerous();

    /**
     * The meta object literal for the '<em><b>Signature</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PERMISSION__SIGNATURE = eINSTANCE.getPermission_Signature();

    /**
     * The meta object literal for the '<em><b>Signature Or System</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PERMISSION__SIGNATURE_OR_SYSTEM = eINSTANCE.getPermission_SignatureOrSystem();

    /**
     * The meta object literal for the '{@link fr.lcis.castav.cdml.cDML.impl.PermissionValueImpl <em>Permission Value</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.lcis.castav.cdml.cDML.impl.PermissionValueImpl
     * @see fr.lcis.castav.cdml.cDML.impl.CDMLPackageImpl#getPermissionValue()
     * @generated
     */
    EClass PERMISSION_VALUE = eINSTANCE.getPermissionValue();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PERMISSION_VALUE__NAME = eINSTANCE.getPermissionValue_Name();

    /**
     * The meta object literal for the '{@link fr.lcis.castav.cdml.cDML.impl.DataFlowImpl <em>Data Flow</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.lcis.castav.cdml.cDML.impl.DataFlowImpl
     * @see fr.lcis.castav.cdml.cDML.impl.CDMLPackageImpl#getDataFlow()
     * @generated
     */
    EClass DATA_FLOW = eINSTANCE.getDataFlow();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DATA_FLOW__NAME = eINSTANCE.getDataFlow_Name();

    /**
     * The meta object literal for the '{@link fr.lcis.castav.cdml.cDML.impl.SinkImpl <em>Sink</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.lcis.castav.cdml.cDML.impl.SinkImpl
     * @see fr.lcis.castav.cdml.cDML.impl.CDMLPackageImpl#getSink()
     * @generated
     */
    EClass SINK = eINSTANCE.getSink();

    /**
     * The meta object literal for the '<em><b>Parameters</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SINK__PARAMETERS = eINSTANCE.getSink_Parameters();

    /**
     * The meta object literal for the '{@link fr.lcis.castav.cdml.cDML.impl.ParameterImpl <em>Parameter</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.lcis.castav.cdml.cDML.impl.ParameterImpl
     * @see fr.lcis.castav.cdml.cDML.impl.CDMLPackageImpl#getParameter()
     * @generated
     */
    EClass PARAMETER = eINSTANCE.getParameter();

    /**
     * The meta object literal for the '<em><b>Wildcard</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PARAMETER__WILDCARD = eINSTANCE.getParameter_Wildcard();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PARAMETER__VALUE = eINSTANCE.getParameter_Value();

    /**
     * The meta object literal for the '<em><b>Source</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PARAMETER__SOURCE = eINSTANCE.getParameter_Source();

    /**
     * The meta object literal for the '<em><b>Origin</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PARAMETER__ORIGIN = eINSTANCE.getParameter_Origin();

    /**
     * The meta object literal for the '{@link fr.lcis.castav.cdml.cDML.impl.SourceImpl <em>Source</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.lcis.castav.cdml.cDML.impl.SourceImpl
     * @see fr.lcis.castav.cdml.cDML.impl.CDMLPackageImpl#getSource()
     * @generated
     */
    EClass SOURCE = eINSTANCE.getSource();

    /**
     * The meta object literal for the '<em><b>Input</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SOURCE__INPUT = eINSTANCE.getSource_Input();

    /**
     * The meta object literal for the '{@link fr.lcis.castav.cdml.cDML.impl.AdaptationImpl <em>Adaptation</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.lcis.castav.cdml.cDML.impl.AdaptationImpl
     * @see fr.lcis.castav.cdml.cDML.impl.CDMLPackageImpl#getAdaptation()
     * @generated
     */
    EClass ADAPTATION = eINSTANCE.getAdaptation();

    /**
     * The meta object literal for the '<em><b>Situations</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ADAPTATION__SITUATIONS = eINSTANCE.getAdaptation_Situations();

    /**
     * The meta object literal for the '<em><b>State</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ADAPTATION__STATE = eINSTANCE.getAdaptation_State();

    /**
     * The meta object literal for the '<em><b>States</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ADAPTATION__STATES = eINSTANCE.getAdaptation_States();

  }

} //CDMLPackage
