/**
 * generated by Xtext 2.29.0
 */
package fr.lcis.castav.cdml.cDML;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Contexts</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.lcis.castav.cdml.cDML.Contexts#getContexts <em>Contexts</em>}</li>
 * </ul>
 *
 * @see fr.lcis.castav.cdml.cDML.CDMLPackage#getContexts()
 * @model
 * @generated
 */
public interface Contexts extends EObject
{
  /**
   * Returns the value of the '<em><b>Contexts</b></em>' containment reference list.
   * The list contents are of type {@link fr.lcis.castav.cdml.cDML.Context}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Contexts</em>' containment reference list.
   * @see fr.lcis.castav.cdml.cDML.CDMLPackage#getContexts_Contexts()
   * @model containment="true"
   * @generated
   */
  EList<Context> getContexts();

} // Contexts
