/**
 * generated by Xtext 2.29.0
 */
package fr.lcis.castav.cdml.cDML;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Permission</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.lcis.castav.cdml.cDML.Permission#isNormal <em>Normal</em>}</li>
 *   <li>{@link fr.lcis.castav.cdml.cDML.Permission#getPermissionValues <em>Permission Values</em>}</li>
 *   <li>{@link fr.lcis.castav.cdml.cDML.Permission#isDangerous <em>Dangerous</em>}</li>
 *   <li>{@link fr.lcis.castav.cdml.cDML.Permission#isSignature <em>Signature</em>}</li>
 *   <li>{@link fr.lcis.castav.cdml.cDML.Permission#isSignatureOrSystem <em>Signature Or System</em>}</li>
 * </ul>
 *
 * @see fr.lcis.castav.cdml.cDML.CDMLPackage#getPermission()
 * @model
 * @generated
 */
public interface Permission extends EObject
{
  /**
   * Returns the value of the '<em><b>Normal</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Normal</em>' attribute.
   * @see #setNormal(boolean)
   * @see fr.lcis.castav.cdml.cDML.CDMLPackage#getPermission_Normal()
   * @model
   * @generated
   */
  boolean isNormal();

  /**
   * Sets the value of the '{@link fr.lcis.castav.cdml.cDML.Permission#isNormal <em>Normal</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Normal</em>' attribute.
   * @see #isNormal()
   * @generated
   */
  void setNormal(boolean value);

  /**
   * Returns the value of the '<em><b>Permission Values</b></em>' containment reference list.
   * The list contents are of type {@link fr.lcis.castav.cdml.cDML.PermissionValue}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Permission Values</em>' containment reference list.
   * @see fr.lcis.castav.cdml.cDML.CDMLPackage#getPermission_PermissionValues()
   * @model containment="true"
   * @generated
   */
  EList<PermissionValue> getPermissionValues();

  /**
   * Returns the value of the '<em><b>Dangerous</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Dangerous</em>' attribute.
   * @see #setDangerous(boolean)
   * @see fr.lcis.castav.cdml.cDML.CDMLPackage#getPermission_Dangerous()
   * @model
   * @generated
   */
  boolean isDangerous();

  /**
   * Sets the value of the '{@link fr.lcis.castav.cdml.cDML.Permission#isDangerous <em>Dangerous</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Dangerous</em>' attribute.
   * @see #isDangerous()
   * @generated
   */
  void setDangerous(boolean value);

  /**
   * Returns the value of the '<em><b>Signature</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Signature</em>' attribute.
   * @see #setSignature(boolean)
   * @see fr.lcis.castav.cdml.cDML.CDMLPackage#getPermission_Signature()
   * @model
   * @generated
   */
  boolean isSignature();

  /**
   * Sets the value of the '{@link fr.lcis.castav.cdml.cDML.Permission#isSignature <em>Signature</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Signature</em>' attribute.
   * @see #isSignature()
   * @generated
   */
  void setSignature(boolean value);

  /**
   * Returns the value of the '<em><b>Signature Or System</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Signature Or System</em>' attribute.
   * @see #setSignatureOrSystem(boolean)
   * @see fr.lcis.castav.cdml.cDML.CDMLPackage#getPermission_SignatureOrSystem()
   * @model
   * @generated
   */
  boolean isSignatureOrSystem();

  /**
   * Sets the value of the '{@link fr.lcis.castav.cdml.cDML.Permission#isSignatureOrSystem <em>Signature Or System</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Signature Or System</em>' attribute.
   * @see #isSignatureOrSystem()
   * @generated
   */
  void setSignatureOrSystem(boolean value);

} // Permission
