/*
 * generated by Xtext 2.29.0
 */
package fr.lcis.castav.cdl.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import fr.lcis.castav.cdl.CDLRuntimeModule;
import fr.lcis.castav.cdl.CDLStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class CDLIdeSetup extends CDLStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new CDLRuntimeModule(), new CDLIdeModule()));
	}
	
}
