/*
 * generated by Xtext 2.28.0
 */
package fr.lcis.castav.vpat;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class VPATRuntimeModule extends AbstractVPATRuntimeModule {
}
