/**
 * generated by Xtext 2.29.0
 */
package fr.lcis.castav.vpat.vPAT;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Permissions</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see fr.lcis.castav.vpat.vPAT.VPATPackage#getPermissions()
 * @model
 * @generated
 */
public interface Permissions extends EObject
{
} // Permissions
