/**
 * generated by Xtext 2.29.0
 */
package fr.lcis.castav.vpat.vPAT;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see fr.lcis.castav.vpat.vPAT.VPATFactory
 * @model kind="package"
 * @generated
 */
public interface VPATPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "vPAT";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.lcis.fr/castav/vpat/VPAT";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "vPAT";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  VPATPackage eINSTANCE = fr.lcis.castav.vpat.vPAT.impl.VPATPackageImpl.init();

  /**
   * The meta object id for the '{@link fr.lcis.castav.vpat.vPAT.impl.VulnerabilityImpl <em>Vulnerability</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.lcis.castav.vpat.vPAT.impl.VulnerabilityImpl
   * @see fr.lcis.castav.vpat.vPAT.impl.VPATPackageImpl#getVulnerability()
   * @generated
   */
  int VULNERABILITY = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VULNERABILITY__NAME = 0;

  /**
   * The feature id for the '<em><b>Description</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VULNERABILITY__DESCRIPTION = 1;

  /**
   * The feature id for the '<em><b>Context</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VULNERABILITY__CONTEXT = 2;

  /**
   * The feature id for the '<em><b>Main Function</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VULNERABILITY__MAIN_FUNCTION = 3;

  /**
   * The feature id for the '<em><b>Function</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VULNERABILITY__FUNCTION = 4;

  /**
   * The number of structural features of the '<em>Vulnerability</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VULNERABILITY_FEATURE_COUNT = 5;

  /**
   * The meta object id for the '{@link fr.lcis.castav.vpat.vPAT.impl.ContextImpl <em>Context</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.lcis.castav.vpat.vPAT.impl.ContextImpl
   * @see fr.lcis.castav.vpat.vPAT.impl.VPATPackageImpl#getContext()
   * @generated
   */
  int CONTEXT = 1;

  /**
   * The feature id for the '<em><b>Permission</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTEXT__PERMISSION = 0;

  /**
   * The feature id for the '<em><b>Value</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTEXT__VALUE = 1;

  /**
   * The feature id for the '<em><b>Network</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTEXT__NETWORK = 2;

  /**
   * The feature id for the '<em><b>Version</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTEXT__VERSION = 3;

  /**
   * The number of structural features of the '<em>Context</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTEXT_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link fr.lcis.castav.vpat.vPAT.impl.VersionImpl <em>Version</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.lcis.castav.vpat.vPAT.impl.VersionImpl
   * @see fr.lcis.castav.vpat.vPAT.impl.VPATPackageImpl#getVersion()
   * @generated
   */
  int VERSION = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VERSION__NAME = 0;

  /**
   * The number of structural features of the '<em>Version</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VERSION_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link fr.lcis.castav.vpat.vPAT.impl.PermissionsImpl <em>Permissions</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.lcis.castav.vpat.vPAT.impl.PermissionsImpl
   * @see fr.lcis.castav.vpat.vPAT.impl.VPATPackageImpl#getPermissions()
   * @generated
   */
  int PERMISSIONS = 3;

  /**
   * The number of structural features of the '<em>Permissions</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PERMISSIONS_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link fr.lcis.castav.vpat.vPAT.impl.PermissionIDImpl <em>Permission ID</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.lcis.castav.vpat.vPAT.impl.PermissionIDImpl
   * @see fr.lcis.castav.vpat.vPAT.impl.VPATPackageImpl#getPermissionID()
   * @generated
   */
  int PERMISSION_ID = 4;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PERMISSION_ID__NAME = 0;

  /**
   * The number of structural features of the '<em>Permission ID</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PERMISSION_ID_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link fr.lcis.castav.vpat.vPAT.impl.NetworkImpl <em>Network</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.lcis.castav.vpat.vPAT.impl.NetworkImpl
   * @see fr.lcis.castav.vpat.vPAT.impl.VPATPackageImpl#getNetwork()
   * @generated
   */
  int NETWORK = 5;

  /**
   * The number of structural features of the '<em>Network</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NETWORK_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link fr.lcis.castav.vpat.vPAT.impl.FunctionImpl <em>Function</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.lcis.castav.vpat.vPAT.impl.FunctionImpl
   * @see fr.lcis.castav.vpat.vPAT.impl.VPATPackageImpl#getFunction()
   * @generated
   */
  int FUNCTION = 6;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNCTION__NAME = 0;

  /**
   * The number of structural features of the '<em>Function</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNCTION_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link fr.lcis.castav.vpat.vPAT.impl.SinkImpl <em>Sink</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.lcis.castav.vpat.vPAT.impl.SinkImpl
   * @see fr.lcis.castav.vpat.vPAT.impl.VPATPackageImpl#getSink()
   * @generated
   */
  int SINK = 7;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SINK__NAME = FUNCTION__NAME;

  /**
   * The feature id for the '<em><b>Parameter</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SINK__PARAMETER = FUNCTION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Sink</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SINK_FEATURE_COUNT = FUNCTION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link fr.lcis.castav.vpat.vPAT.impl.ParameterImpl <em>Parameter</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.lcis.castav.vpat.vPAT.impl.ParameterImpl
   * @see fr.lcis.castav.vpat.vPAT.impl.VPATPackageImpl#getParameter()
   * @generated
   */
  int PARAMETER = 8;

  /**
   * The feature id for the '<em><b>Origin</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAMETER__ORIGIN = 0;

  /**
   * The feature id for the '<em><b>Static</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAMETER__STATIC = 1;

  /**
   * The feature id for the '<em><b>Any Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAMETER__ANY_VALUE = 2;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAMETER__VALUE = 3;

  /**
   * The number of structural features of the '<em>Parameter</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAMETER_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link fr.lcis.castav.vpat.vPAT.impl.InflowImpl <em>Inflow</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.lcis.castav.vpat.vPAT.impl.InflowImpl
   * @see fr.lcis.castav.vpat.vPAT.impl.VPATPackageImpl#getInflow()
   * @generated
   */
  int INFLOW = 9;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INFLOW__NAME = FUNCTION__NAME;

  /**
   * The feature id for the '<em><b>Method</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INFLOW__METHOD = FUNCTION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Inflow</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INFLOW_FEATURE_COUNT = FUNCTION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link fr.lcis.castav.vpat.vPAT.impl.SourceImpl <em>Source</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.lcis.castav.vpat.vPAT.impl.SourceImpl
   * @see fr.lcis.castav.vpat.vPAT.impl.VPATPackageImpl#getSource()
   * @generated
   */
  int SOURCE = 10;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SOURCE__NAME = INFLOW__NAME;

  /**
   * The feature id for the '<em><b>Method</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SOURCE__METHOD = INFLOW__METHOD;

  /**
   * The feature id for the '<em><b>Any Private</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SOURCE__ANY_PRIVATE = INFLOW_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Source</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SOURCE_FEATURE_COUNT = INFLOW_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link fr.lcis.castav.vpat.vPAT.impl.InputImpl <em>Input</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.lcis.castav.vpat.vPAT.impl.InputImpl
   * @see fr.lcis.castav.vpat.vPAT.impl.VPATPackageImpl#getInput()
   * @generated
   */
  int INPUT = 11;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INPUT__NAME = INFLOW__NAME;

  /**
   * The feature id for the '<em><b>Method</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INPUT__METHOD = INFLOW__METHOD;

  /**
   * The number of structural features of the '<em>Input</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INPUT_FEATURE_COUNT = INFLOW_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link fr.lcis.castav.vpat.vPAT.impl.PermissionImpl <em>Permission</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.lcis.castav.vpat.vPAT.impl.PermissionImpl
   * @see fr.lcis.castav.vpat.vPAT.impl.VPATPackageImpl#getPermission()
   * @generated
   */
  int PERMISSION = 12;

  /**
   * The feature id for the '<em><b>Name</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PERMISSION__NAME = PERMISSIONS_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Permission</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PERMISSION_FEATURE_COUNT = PERMISSIONS_FEATURE_COUNT + 1;


  /**
   * Returns the meta object for class '{@link fr.lcis.castav.vpat.vPAT.Vulnerability <em>Vulnerability</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Vulnerability</em>'.
   * @see fr.lcis.castav.vpat.vPAT.Vulnerability
   * @generated
   */
  EClass getVulnerability();

  /**
   * Returns the meta object for the attribute '{@link fr.lcis.castav.vpat.vPAT.Vulnerability#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see fr.lcis.castav.vpat.vPAT.Vulnerability#getName()
   * @see #getVulnerability()
   * @generated
   */
  EAttribute getVulnerability_Name();

  /**
   * Returns the meta object for the attribute '{@link fr.lcis.castav.vpat.vPAT.Vulnerability#getDescription <em>Description</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Description</em>'.
   * @see fr.lcis.castav.vpat.vPAT.Vulnerability#getDescription()
   * @see #getVulnerability()
   * @generated
   */
  EAttribute getVulnerability_Description();

  /**
   * Returns the meta object for the containment reference list '{@link fr.lcis.castav.vpat.vPAT.Vulnerability#getContext <em>Context</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Context</em>'.
   * @see fr.lcis.castav.vpat.vPAT.Vulnerability#getContext()
   * @see #getVulnerability()
   * @generated
   */
  EReference getVulnerability_Context();

  /**
   * Returns the meta object for the containment reference '{@link fr.lcis.castav.vpat.vPAT.Vulnerability#getMainFunction <em>Main Function</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Main Function</em>'.
   * @see fr.lcis.castav.vpat.vPAT.Vulnerability#getMainFunction()
   * @see #getVulnerability()
   * @generated
   */
  EReference getVulnerability_MainFunction();

  /**
   * Returns the meta object for the containment reference list '{@link fr.lcis.castav.vpat.vPAT.Vulnerability#getFunction <em>Function</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Function</em>'.
   * @see fr.lcis.castav.vpat.vPAT.Vulnerability#getFunction()
   * @see #getVulnerability()
   * @generated
   */
  EReference getVulnerability_Function();

  /**
   * Returns the meta object for class '{@link fr.lcis.castav.vpat.vPAT.Context <em>Context</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Context</em>'.
   * @see fr.lcis.castav.vpat.vPAT.Context
   * @generated
   */
  EClass getContext();

  /**
   * Returns the meta object for the attribute '{@link fr.lcis.castav.vpat.vPAT.Context#isPermission <em>Permission</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Permission</em>'.
   * @see fr.lcis.castav.vpat.vPAT.Context#isPermission()
   * @see #getContext()
   * @generated
   */
  EAttribute getContext_Permission();

  /**
   * Returns the meta object for the containment reference '{@link fr.lcis.castav.vpat.vPAT.Context#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Value</em>'.
   * @see fr.lcis.castav.vpat.vPAT.Context#getValue()
   * @see #getContext()
   * @generated
   */
  EReference getContext_Value();

  /**
   * Returns the meta object for the attribute '{@link fr.lcis.castav.vpat.vPAT.Context#isNetwork <em>Network</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Network</em>'.
   * @see fr.lcis.castav.vpat.vPAT.Context#isNetwork()
   * @see #getContext()
   * @generated
   */
  EAttribute getContext_Network();

  /**
   * Returns the meta object for the attribute '{@link fr.lcis.castav.vpat.vPAT.Context#isVersion <em>Version</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Version</em>'.
   * @see fr.lcis.castav.vpat.vPAT.Context#isVersion()
   * @see #getContext()
   * @generated
   */
  EAttribute getContext_Version();

  /**
   * Returns the meta object for class '{@link fr.lcis.castav.vpat.vPAT.Version <em>Version</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Version</em>'.
   * @see fr.lcis.castav.vpat.vPAT.Version
   * @generated
   */
  EClass getVersion();

  /**
   * Returns the meta object for the attribute '{@link fr.lcis.castav.vpat.vPAT.Version#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see fr.lcis.castav.vpat.vPAT.Version#getName()
   * @see #getVersion()
   * @generated
   */
  EAttribute getVersion_Name();

  /**
   * Returns the meta object for class '{@link fr.lcis.castav.vpat.vPAT.Permissions <em>Permissions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Permissions</em>'.
   * @see fr.lcis.castav.vpat.vPAT.Permissions
   * @generated
   */
  EClass getPermissions();

  /**
   * Returns the meta object for class '{@link fr.lcis.castav.vpat.vPAT.PermissionID <em>Permission ID</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Permission ID</em>'.
   * @see fr.lcis.castav.vpat.vPAT.PermissionID
   * @generated
   */
  EClass getPermissionID();

  /**
   * Returns the meta object for the attribute '{@link fr.lcis.castav.vpat.vPAT.PermissionID#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see fr.lcis.castav.vpat.vPAT.PermissionID#getName()
   * @see #getPermissionID()
   * @generated
   */
  EAttribute getPermissionID_Name();

  /**
   * Returns the meta object for class '{@link fr.lcis.castav.vpat.vPAT.Network <em>Network</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Network</em>'.
   * @see fr.lcis.castav.vpat.vPAT.Network
   * @generated
   */
  EClass getNetwork();

  /**
   * Returns the meta object for class '{@link fr.lcis.castav.vpat.vPAT.Function <em>Function</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Function</em>'.
   * @see fr.lcis.castav.vpat.vPAT.Function
   * @generated
   */
  EClass getFunction();

  /**
   * Returns the meta object for the attribute '{@link fr.lcis.castav.vpat.vPAT.Function#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see fr.lcis.castav.vpat.vPAT.Function#getName()
   * @see #getFunction()
   * @generated
   */
  EAttribute getFunction_Name();

  /**
   * Returns the meta object for class '{@link fr.lcis.castav.vpat.vPAT.Sink <em>Sink</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Sink</em>'.
   * @see fr.lcis.castav.vpat.vPAT.Sink
   * @generated
   */
  EClass getSink();

  /**
   * Returns the meta object for the containment reference list '{@link fr.lcis.castav.vpat.vPAT.Sink#getParameter <em>Parameter</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Parameter</em>'.
   * @see fr.lcis.castav.vpat.vPAT.Sink#getParameter()
   * @see #getSink()
   * @generated
   */
  EReference getSink_Parameter();

  /**
   * Returns the meta object for class '{@link fr.lcis.castav.vpat.vPAT.Parameter <em>Parameter</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Parameter</em>'.
   * @see fr.lcis.castav.vpat.vPAT.Parameter
   * @generated
   */
  EClass getParameter();

  /**
   * Returns the meta object for the reference '{@link fr.lcis.castav.vpat.vPAT.Parameter#getOrigin <em>Origin</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Origin</em>'.
   * @see fr.lcis.castav.vpat.vPAT.Parameter#getOrigin()
   * @see #getParameter()
   * @generated
   */
  EReference getParameter_Origin();

  /**
   * Returns the meta object for the attribute '{@link fr.lcis.castav.vpat.vPAT.Parameter#isStatic <em>Static</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Static</em>'.
   * @see fr.lcis.castav.vpat.vPAT.Parameter#isStatic()
   * @see #getParameter()
   * @generated
   */
  EAttribute getParameter_Static();

  /**
   * Returns the meta object for the attribute '{@link fr.lcis.castav.vpat.vPAT.Parameter#isAnyValue <em>Any Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Any Value</em>'.
   * @see fr.lcis.castav.vpat.vPAT.Parameter#isAnyValue()
   * @see #getParameter()
   * @generated
   */
  EAttribute getParameter_AnyValue();

  /**
   * Returns the meta object for the attribute '{@link fr.lcis.castav.vpat.vPAT.Parameter#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see fr.lcis.castav.vpat.vPAT.Parameter#getValue()
   * @see #getParameter()
   * @generated
   */
  EAttribute getParameter_Value();

  /**
   * Returns the meta object for class '{@link fr.lcis.castav.vpat.vPAT.Inflow <em>Inflow</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Inflow</em>'.
   * @see fr.lcis.castav.vpat.vPAT.Inflow
   * @generated
   */
  EClass getInflow();

  /**
   * Returns the meta object for the attribute '{@link fr.lcis.castav.vpat.vPAT.Inflow#getMethod <em>Method</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Method</em>'.
   * @see fr.lcis.castav.vpat.vPAT.Inflow#getMethod()
   * @see #getInflow()
   * @generated
   */
  EAttribute getInflow_Method();

  /**
   * Returns the meta object for class '{@link fr.lcis.castav.vpat.vPAT.Source <em>Source</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Source</em>'.
   * @see fr.lcis.castav.vpat.vPAT.Source
   * @generated
   */
  EClass getSource();

  /**
   * Returns the meta object for the attribute '{@link fr.lcis.castav.vpat.vPAT.Source#isAnyPrivate <em>Any Private</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Any Private</em>'.
   * @see fr.lcis.castav.vpat.vPAT.Source#isAnyPrivate()
   * @see #getSource()
   * @generated
   */
  EAttribute getSource_AnyPrivate();

  /**
   * Returns the meta object for class '{@link fr.lcis.castav.vpat.vPAT.Input <em>Input</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Input</em>'.
   * @see fr.lcis.castav.vpat.vPAT.Input
   * @generated
   */
  EClass getInput();

  /**
   * Returns the meta object for class '{@link fr.lcis.castav.vpat.vPAT.Permission <em>Permission</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Permission</em>'.
   * @see fr.lcis.castav.vpat.vPAT.Permission
   * @generated
   */
  EClass getPermission();

  /**
   * Returns the meta object for the containment reference '{@link fr.lcis.castav.vpat.vPAT.Permission#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Name</em>'.
   * @see fr.lcis.castav.vpat.vPAT.Permission#getName()
   * @see #getPermission()
   * @generated
   */
  EReference getPermission_Name();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  VPATFactory getVPATFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link fr.lcis.castav.vpat.vPAT.impl.VulnerabilityImpl <em>Vulnerability</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.lcis.castav.vpat.vPAT.impl.VulnerabilityImpl
     * @see fr.lcis.castav.vpat.vPAT.impl.VPATPackageImpl#getVulnerability()
     * @generated
     */
    EClass VULNERABILITY = eINSTANCE.getVulnerability();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VULNERABILITY__NAME = eINSTANCE.getVulnerability_Name();

    /**
     * The meta object literal for the '<em><b>Description</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VULNERABILITY__DESCRIPTION = eINSTANCE.getVulnerability_Description();

    /**
     * The meta object literal for the '<em><b>Context</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference VULNERABILITY__CONTEXT = eINSTANCE.getVulnerability_Context();

    /**
     * The meta object literal for the '<em><b>Main Function</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference VULNERABILITY__MAIN_FUNCTION = eINSTANCE.getVulnerability_MainFunction();

    /**
     * The meta object literal for the '<em><b>Function</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference VULNERABILITY__FUNCTION = eINSTANCE.getVulnerability_Function();

    /**
     * The meta object literal for the '{@link fr.lcis.castav.vpat.vPAT.impl.ContextImpl <em>Context</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.lcis.castav.vpat.vPAT.impl.ContextImpl
     * @see fr.lcis.castav.vpat.vPAT.impl.VPATPackageImpl#getContext()
     * @generated
     */
    EClass CONTEXT = eINSTANCE.getContext();

    /**
     * The meta object literal for the '<em><b>Permission</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONTEXT__PERMISSION = eINSTANCE.getContext_Permission();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONTEXT__VALUE = eINSTANCE.getContext_Value();

    /**
     * The meta object literal for the '<em><b>Network</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONTEXT__NETWORK = eINSTANCE.getContext_Network();

    /**
     * The meta object literal for the '<em><b>Version</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONTEXT__VERSION = eINSTANCE.getContext_Version();

    /**
     * The meta object literal for the '{@link fr.lcis.castav.vpat.vPAT.impl.VersionImpl <em>Version</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.lcis.castav.vpat.vPAT.impl.VersionImpl
     * @see fr.lcis.castav.vpat.vPAT.impl.VPATPackageImpl#getVersion()
     * @generated
     */
    EClass VERSION = eINSTANCE.getVersion();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VERSION__NAME = eINSTANCE.getVersion_Name();

    /**
     * The meta object literal for the '{@link fr.lcis.castav.vpat.vPAT.impl.PermissionsImpl <em>Permissions</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.lcis.castav.vpat.vPAT.impl.PermissionsImpl
     * @see fr.lcis.castav.vpat.vPAT.impl.VPATPackageImpl#getPermissions()
     * @generated
     */
    EClass PERMISSIONS = eINSTANCE.getPermissions();

    /**
     * The meta object literal for the '{@link fr.lcis.castav.vpat.vPAT.impl.PermissionIDImpl <em>Permission ID</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.lcis.castav.vpat.vPAT.impl.PermissionIDImpl
     * @see fr.lcis.castav.vpat.vPAT.impl.VPATPackageImpl#getPermissionID()
     * @generated
     */
    EClass PERMISSION_ID = eINSTANCE.getPermissionID();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PERMISSION_ID__NAME = eINSTANCE.getPermissionID_Name();

    /**
     * The meta object literal for the '{@link fr.lcis.castav.vpat.vPAT.impl.NetworkImpl <em>Network</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.lcis.castav.vpat.vPAT.impl.NetworkImpl
     * @see fr.lcis.castav.vpat.vPAT.impl.VPATPackageImpl#getNetwork()
     * @generated
     */
    EClass NETWORK = eINSTANCE.getNetwork();

    /**
     * The meta object literal for the '{@link fr.lcis.castav.vpat.vPAT.impl.FunctionImpl <em>Function</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.lcis.castav.vpat.vPAT.impl.FunctionImpl
     * @see fr.lcis.castav.vpat.vPAT.impl.VPATPackageImpl#getFunction()
     * @generated
     */
    EClass FUNCTION = eINSTANCE.getFunction();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FUNCTION__NAME = eINSTANCE.getFunction_Name();

    /**
     * The meta object literal for the '{@link fr.lcis.castav.vpat.vPAT.impl.SinkImpl <em>Sink</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.lcis.castav.vpat.vPAT.impl.SinkImpl
     * @see fr.lcis.castav.vpat.vPAT.impl.VPATPackageImpl#getSink()
     * @generated
     */
    EClass SINK = eINSTANCE.getSink();

    /**
     * The meta object literal for the '<em><b>Parameter</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SINK__PARAMETER = eINSTANCE.getSink_Parameter();

    /**
     * The meta object literal for the '{@link fr.lcis.castav.vpat.vPAT.impl.ParameterImpl <em>Parameter</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.lcis.castav.vpat.vPAT.impl.ParameterImpl
     * @see fr.lcis.castav.vpat.vPAT.impl.VPATPackageImpl#getParameter()
     * @generated
     */
    EClass PARAMETER = eINSTANCE.getParameter();

    /**
     * The meta object literal for the '<em><b>Origin</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PARAMETER__ORIGIN = eINSTANCE.getParameter_Origin();

    /**
     * The meta object literal for the '<em><b>Static</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PARAMETER__STATIC = eINSTANCE.getParameter_Static();

    /**
     * The meta object literal for the '<em><b>Any Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PARAMETER__ANY_VALUE = eINSTANCE.getParameter_AnyValue();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PARAMETER__VALUE = eINSTANCE.getParameter_Value();

    /**
     * The meta object literal for the '{@link fr.lcis.castav.vpat.vPAT.impl.InflowImpl <em>Inflow</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.lcis.castav.vpat.vPAT.impl.InflowImpl
     * @see fr.lcis.castav.vpat.vPAT.impl.VPATPackageImpl#getInflow()
     * @generated
     */
    EClass INFLOW = eINSTANCE.getInflow();

    /**
     * The meta object literal for the '<em><b>Method</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INFLOW__METHOD = eINSTANCE.getInflow_Method();

    /**
     * The meta object literal for the '{@link fr.lcis.castav.vpat.vPAT.impl.SourceImpl <em>Source</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.lcis.castav.vpat.vPAT.impl.SourceImpl
     * @see fr.lcis.castav.vpat.vPAT.impl.VPATPackageImpl#getSource()
     * @generated
     */
    EClass SOURCE = eINSTANCE.getSource();

    /**
     * The meta object literal for the '<em><b>Any Private</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SOURCE__ANY_PRIVATE = eINSTANCE.getSource_AnyPrivate();

    /**
     * The meta object literal for the '{@link fr.lcis.castav.vpat.vPAT.impl.InputImpl <em>Input</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.lcis.castav.vpat.vPAT.impl.InputImpl
     * @see fr.lcis.castav.vpat.vPAT.impl.VPATPackageImpl#getInput()
     * @generated
     */
    EClass INPUT = eINSTANCE.getInput();

    /**
     * The meta object literal for the '{@link fr.lcis.castav.vpat.vPAT.impl.PermissionImpl <em>Permission</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.lcis.castav.vpat.vPAT.impl.PermissionImpl
     * @see fr.lcis.castav.vpat.vPAT.impl.VPATPackageImpl#getPermission()
     * @generated
     */
    EClass PERMISSION = eINSTANCE.getPermission();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PERMISSION__NAME = eINSTANCE.getPermission_Name();

  }

} //VPATPackage
