/*
 * generated by Xtext 2.28.0
 */
package fr.lcis.castav.vpat.validation;

import org.eclipse.xtext.validation.Check;

import fr.lcis.castav.vpat.vPAT.Function;
import fr.lcis.castav.vpat.vPAT.Vulnerability;

/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
public class VPATValidator extends AbstractVPATValidator {
	
//	public static final String INVALID_NAME = "invalidName";
//
//	@Check
//	public void checkGreetingStartsWithCapital(Greeting greeting) {
//		if (!Character.isUpperCase(greeting.getName().charAt(0))) {
//			warning("Name should start with a capital",
//					VPATPackage.Literals.GREETING__NAME,
//					INVALID_NAME);
//		}
//	}
	
}
